[2022-05-11 06:55:50,508] {processor.py:163} INFO - Started process (PID=28839) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:55:50,657] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:55:50,761] {logging_mixin.py:109} INFO - [2022-05-11 06:55:50,760] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:55:51,704] {logging_mixin.py:109} INFO - [2022-05-11 06:55:51,660] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:55:51,738] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:55:51,864] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 1.359 seconds
[2022-05-11 06:56:22,191] {processor.py:163} INFO - Started process (PID=28903) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:56:22,193] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:56:22,194] {logging_mixin.py:109} INFO - [2022-05-11 06:56:22,194] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:56:22,252] {logging_mixin.py:109} INFO - [2022-05-11 06:56:22,240] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:56:22,258] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:56:22,307] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.120 seconds
[2022-05-11 06:56:52,779] {processor.py:163} INFO - Started process (PID=28966) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:56:52,781] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:56:52,782] {logging_mixin.py:109} INFO - [2022-05-11 06:56:52,782] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:56:52,805] {logging_mixin.py:109} INFO - [2022-05-11 06:56:52,801] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:56:52,806] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:56:52,829] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.053 seconds
[2022-05-11 06:57:23,235] {processor.py:163} INFO - Started process (PID=29039) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:57:23,237] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:57:23,239] {logging_mixin.py:109} INFO - [2022-05-11 06:57:23,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:57:23,287] {logging_mixin.py:109} INFO - [2022-05-11 06:57:23,280] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:57:23,290] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:57:23,317] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.086 seconds
[2022-05-11 06:57:53,487] {processor.py:163} INFO - Started process (PID=29102) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:57:53,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:57:53,491] {logging_mixin.py:109} INFO - [2022-05-11 06:57:53,491] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:57:53,536] {logging_mixin.py:109} INFO - [2022-05-11 06:57:53,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:57:53,538] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:57:53,563] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.079 seconds
[2022-05-11 06:58:24,059] {processor.py:163} INFO - Started process (PID=29175) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:58:24,060] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:58:24,061] {logging_mixin.py:109} INFO - [2022-05-11 06:58:24,061] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:58:24,097] {logging_mixin.py:109} INFO - [2022-05-11 06:58:24,091] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:58:24,099] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:58:24,124] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.068 seconds
[2022-05-11 06:58:54,294] {processor.py:163} INFO - Started process (PID=29237) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:58:54,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:58:54,296] {logging_mixin.py:109} INFO - [2022-05-11 06:58:54,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:58:54,338] {logging_mixin.py:109} INFO - [2022-05-11 06:58:54,331] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:58:54,342] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:58:54,371] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.080 seconds
[2022-05-11 06:59:24,475] {processor.py:163} INFO - Started process (PID=29310) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:59:24,477] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:59:24,478] {logging_mixin.py:109} INFO - [2022-05-11 06:59:24,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:59:24,518] {logging_mixin.py:109} INFO - [2022-05-11 06:59:24,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:59:24,521] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:59:24,551] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.079 seconds
[2022-05-11 06:59:54,600] {processor.py:163} INFO - Started process (PID=29373) to work on /opt/airflow/dags/ej10.py
[2022-05-11 06:59:54,601] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 06:59:54,602] {logging_mixin.py:109} INFO - [2022-05-11 06:59:54,602] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 06:59:54,628] {logging_mixin.py:109} INFO - [2022-05-11 06:59:54,623] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:59:54,631] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 06:59:54,661] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.064 seconds
[2022-05-11 07:00:25,033] {processor.py:163} INFO - Started process (PID=29447) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:00:25,035] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:00:25,036] {logging_mixin.py:109} INFO - [2022-05-11 07:00:25,036] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:00:25,088] {logging_mixin.py:109} INFO - [2022-05-11 07:00:25,079] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:00:25,091] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:00:25,119] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.090 seconds
[2022-05-11 07:00:55,726] {processor.py:163} INFO - Started process (PID=29511) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:00:55,728] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:00:55,729] {logging_mixin.py:109} INFO - [2022-05-11 07:00:55,729] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:00:55,769] {logging_mixin.py:109} INFO - [2022-05-11 07:00:55,763] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:00:55,771] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:00:55,794] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.071 seconds
[2022-05-11 07:01:26,390] {processor.py:163} INFO - Started process (PID=29583) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:01:26,392] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:01:26,393] {logging_mixin.py:109} INFO - [2022-05-11 07:01:26,393] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:01:26,446] {logging_mixin.py:109} INFO - [2022-05-11 07:01:26,436] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:01:26,449] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:01:26,479] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.091 seconds
[2022-05-11 07:01:56,712] {processor.py:163} INFO - Started process (PID=29646) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:01:56,714] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:01:56,715] {logging_mixin.py:109} INFO - [2022-05-11 07:01:56,715] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:01:56,749] {logging_mixin.py:109} INFO - [2022-05-11 07:01:56,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:01:56,751] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:01:56,775] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.066 seconds
[2022-05-11 07:02:27,150] {processor.py:163} INFO - Started process (PID=29720) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:02:27,152] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:02:27,153] {logging_mixin.py:109} INFO - [2022-05-11 07:02:27,153] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:02:27,182] {logging_mixin.py:109} INFO - [2022-05-11 07:02:27,177] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:02:27,184] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:02:27,211] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.064 seconds
[2022-05-11 07:02:57,830] {processor.py:163} INFO - Started process (PID=29793) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:02:57,832] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:02:57,833] {logging_mixin.py:109} INFO - [2022-05-11 07:02:57,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:02:57,873] {logging_mixin.py:109} INFO - [2022-05-11 07:02:57,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:02:57,876] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:02:57,906] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.081 seconds
[2022-05-11 07:03:28,314] {processor.py:163} INFO - Started process (PID=29855) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:03:28,316] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:03:28,317] {logging_mixin.py:109} INFO - [2022-05-11 07:03:28,317] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:03:28,348] {logging_mixin.py:109} INFO - [2022-05-11 07:03:28,343] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:03:28,350] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:03:28,379] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.069 seconds
[2022-05-11 07:03:59,097] {processor.py:163} INFO - Started process (PID=29927) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:03:59,099] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:03:59,100] {logging_mixin.py:109} INFO - [2022-05-11 07:03:59,100] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:03:59,133] {logging_mixin.py:109} INFO - [2022-05-11 07:03:59,129] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:03:59,135] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:03:59,161] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.067 seconds
[2022-05-11 07:04:29,652] {processor.py:163} INFO - Started process (PID=29990) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:04:29,654] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:04:29,655] {logging_mixin.py:109} INFO - [2022-05-11 07:04:29,655] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:04:29,698] {logging_mixin.py:109} INFO - [2022-05-11 07:04:29,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:04:29,701] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:04:29,727] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.079 seconds
[2022-05-11 07:05:00,134] {processor.py:163} INFO - Started process (PID=30064) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:05:00,136] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:05:00,137] {logging_mixin.py:109} INFO - [2022-05-11 07:05:00,137] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:05:00,172] {logging_mixin.py:109} INFO - [2022-05-11 07:05:00,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:05:00,174] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:05:00,200] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.069 seconds
[2022-05-11 07:05:30,636] {processor.py:163} INFO - Started process (PID=30128) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:05:30,637] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:05:30,638] {logging_mixin.py:109} INFO - [2022-05-11 07:05:30,638] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:05:30,673] {logging_mixin.py:109} INFO - [2022-05-11 07:05:30,665] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:05:30,675] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:05:30,703] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.071 seconds
[2022-05-11 07:06:00,982] {processor.py:163} INFO - Started process (PID=30201) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:06:00,984] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:06:00,985] {logging_mixin.py:109} INFO - [2022-05-11 07:06:00,985] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:06:01,024] {logging_mixin.py:109} INFO - [2022-05-11 07:06:01,016] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:06:01,026] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:06:01,050] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.070 seconds
[2022-05-11 07:06:31,516] {processor.py:163} INFO - Started process (PID=30263) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:06:31,518] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:06:31,519] {logging_mixin.py:109} INFO - [2022-05-11 07:06:31,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:06:31,558] {logging_mixin.py:109} INFO - [2022-05-11 07:06:31,555] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:06:31,560] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:06:31,581] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.068 seconds
[2022-05-11 07:07:01,996] {processor.py:163} INFO - Started process (PID=30334) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:07:01,998] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:07:01,999] {logging_mixin.py:109} INFO - [2022-05-11 07:07:01,999] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:07:02,019] {logging_mixin.py:109} INFO - [2022-05-11 07:07:02,016] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:07:02,020] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:07:02,047] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.054 seconds
[2022-05-11 07:07:32,441] {processor.py:163} INFO - Started process (PID=30407) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:07:32,442] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:07:32,443] {logging_mixin.py:109} INFO - [2022-05-11 07:07:32,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:07:32,478] {logging_mixin.py:109} INFO - [2022-05-11 07:07:32,474] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:07:32,479] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:07:32,502] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.066 seconds
[2022-05-11 07:08:02,576] {processor.py:163} INFO - Started process (PID=30469) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:08:02,578] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:08:02,579] {logging_mixin.py:109} INFO - [2022-05-11 07:08:02,579] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:08:02,623] {logging_mixin.py:109} INFO - [2022-05-11 07:08:02,616] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:08:02,625] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:08:02,650] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.078 seconds
[2022-05-11 07:08:33,126] {processor.py:163} INFO - Started process (PID=30541) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:08:33,127] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:08:33,128] {logging_mixin.py:109} INFO - [2022-05-11 07:08:33,128] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:08:33,160] {logging_mixin.py:109} INFO - [2022-05-11 07:08:33,153] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:08:33,162] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:08:33,185] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.063 seconds
[2022-05-11 07:09:03,344] {processor.py:163} INFO - Started process (PID=30604) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:09:03,346] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:09:03,347] {logging_mixin.py:109} INFO - [2022-05-11 07:09:03,347] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:09:03,387] {logging_mixin.py:109} INFO - [2022-05-11 07:09:03,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:09:03,389] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:09:03,417] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.076 seconds
[2022-05-11 07:09:34,048] {processor.py:163} INFO - Started process (PID=30676) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:09:34,050] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:09:34,051] {logging_mixin.py:109} INFO - [2022-05-11 07:09:34,051] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:09:34,078] {logging_mixin.py:109} INFO - [2022-05-11 07:09:34,073] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:09:34,080] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:09:34,110] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.065 seconds
[2022-05-11 07:10:04,413] {processor.py:163} INFO - Started process (PID=30738) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:10:04,415] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:10:04,416] {logging_mixin.py:109} INFO - [2022-05-11 07:10:04,416] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:10:04,455] {logging_mixin.py:109} INFO - [2022-05-11 07:10:04,447] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:10:04,456] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:10:04,484] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.073 seconds
[2022-05-11 07:10:35,053] {processor.py:163} INFO - Started process (PID=30811) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:10:35,055] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:10:35,056] {logging_mixin.py:109} INFO - [2022-05-11 07:10:35,056] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:10:35,102] {logging_mixin.py:109} INFO - [2022-05-11 07:10:35,095] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:10:35,104] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:10:35,134] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.084 seconds
[2022-05-11 07:11:05,794] {processor.py:163} INFO - Started process (PID=30875) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:11:05,796] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:11:05,797] {logging_mixin.py:109} INFO - [2022-05-11 07:11:05,797] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:11:05,841] {logging_mixin.py:109} INFO - [2022-05-11 07:11:05,832] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:11:05,844] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:11:05,866] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.077 seconds
[2022-05-11 07:11:36,583] {processor.py:163} INFO - Started process (PID=30947) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:11:36,585] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:11:36,586] {logging_mixin.py:109} INFO - [2022-05-11 07:11:36,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:11:36,623] {logging_mixin.py:109} INFO - [2022-05-11 07:11:36,617] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:11:36,626] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:11:36,656] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.076 seconds
[2022-05-11 07:12:07,018] {processor.py:163} INFO - Started process (PID=31020) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:12:07,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:12:07,020] {logging_mixin.py:109} INFO - [2022-05-11 07:12:07,020] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:12:07,040] {logging_mixin.py:109} INFO - [2022-05-11 07:12:07,037] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:12:07,041] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:12:07,065] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.050 seconds
[2022-05-11 07:12:37,948] {processor.py:163} INFO - Started process (PID=31084) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:12:37,949] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:12:37,950] {logging_mixin.py:109} INFO - [2022-05-11 07:12:37,950] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:12:37,969] {logging_mixin.py:109} INFO - [2022-05-11 07:12:37,966] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:12:37,970] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:12:37,996] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.051 seconds
[2022-05-11 07:13:08,244] {processor.py:163} INFO - Started process (PID=31157) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:13:08,245] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:13:08,246] {logging_mixin.py:109} INFO - [2022-05-11 07:13:08,246] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:13:08,265] {logging_mixin.py:109} INFO - [2022-05-11 07:13:08,262] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:13:08,266] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:13:08,288] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.047 seconds
[2022-05-11 07:13:38,528] {processor.py:163} INFO - Started process (PID=31221) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:13:38,530] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:13:38,532] {logging_mixin.py:109} INFO - [2022-05-11 07:13:38,531] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:13:38,556] {logging_mixin.py:109} INFO - [2022-05-11 07:13:38,552] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:13:38,557] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:13:38,587] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.062 seconds
[2022-05-11 07:14:08,965] {processor.py:163} INFO - Started process (PID=31293) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:14:08,967] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:14:08,968] {logging_mixin.py:109} INFO - [2022-05-11 07:14:08,967] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:14:08,983] {logging_mixin.py:109} INFO - [2022-05-11 07:14:08,981] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:14:08,984] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:14:09,006] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.044 seconds
[2022-05-11 07:14:39,574] {processor.py:163} INFO - Started process (PID=31356) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:14:39,577] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:14:39,578] {logging_mixin.py:109} INFO - [2022-05-11 07:14:39,578] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:14:39,595] {logging_mixin.py:109} INFO - [2022-05-11 07:14:39,592] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:14:39,596] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:14:39,623] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.052 seconds
[2022-05-11 07:15:09,714] {processor.py:163} INFO - Started process (PID=31429) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:15:09,715] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:15:09,716] {logging_mixin.py:109} INFO - [2022-05-11 07:15:09,716] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:15:09,740] {logging_mixin.py:109} INFO - [2022-05-11 07:15:09,736] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:15:09,741] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:15:09,764] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.053 seconds
[2022-05-11 07:15:39,984] {processor.py:163} INFO - Started process (PID=31494) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:15:39,986] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:15:39,986] {logging_mixin.py:109} INFO - [2022-05-11 07:15:39,986] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:15:40,009] {logging_mixin.py:109} INFO - [2022-05-11 07:15:40,005] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:15:40,010] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:15:40,033] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.052 seconds
[2022-05-11 07:16:10,498] {processor.py:163} INFO - Started process (PID=31568) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:16:10,500] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:16:10,500] {logging_mixin.py:109} INFO - [2022-05-11 07:16:10,500] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:16:10,519] {logging_mixin.py:109} INFO - [2022-05-11 07:16:10,516] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:16:10,520] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:16:10,545] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.050 seconds
[2022-05-11 07:16:40,870] {processor.py:163} INFO - Started process (PID=31631) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:16:40,872] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:16:40,874] {logging_mixin.py:109} INFO - [2022-05-11 07:16:40,874] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:16:40,900] {logging_mixin.py:109} INFO - [2022-05-11 07:16:40,895] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:16:40,902] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:16:40,933] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.067 seconds
[2022-05-11 07:17:11,461] {processor.py:163} INFO - Started process (PID=31703) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:17:11,463] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:17:11,463] {logging_mixin.py:109} INFO - [2022-05-11 07:17:11,463] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:17:11,495] {logging_mixin.py:109} INFO - [2022-05-11 07:17:11,488] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:17:11,496] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:17:11,526] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.069 seconds
[2022-05-11 07:17:41,971] {processor.py:163} INFO - Started process (PID=31767) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:17:41,973] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:17:41,974] {logging_mixin.py:109} INFO - [2022-05-11 07:17:41,973] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:17:41,993] {logging_mixin.py:109} INFO - [2022-05-11 07:17:41,990] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:17:41,994] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:17:42,023] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.057 seconds
[2022-05-11 07:18:12,663] {processor.py:163} INFO - Started process (PID=31840) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:18:12,665] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:18:12,666] {logging_mixin.py:109} INFO - [2022-05-11 07:18:12,666] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:18:12,687] {logging_mixin.py:109} INFO - [2022-05-11 07:18:12,683] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:18:12,689] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:18:12,715] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.055 seconds
[2022-05-11 07:18:42,850] {processor.py:163} INFO - Started process (PID=31902) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:18:42,851] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:18:42,852] {logging_mixin.py:109} INFO - [2022-05-11 07:18:42,852] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:18:42,869] {logging_mixin.py:109} INFO - [2022-05-11 07:18:42,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:18:42,870] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:18:42,897] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.050 seconds
[2022-05-11 07:19:13,023] {processor.py:163} INFO - Started process (PID=31965) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:19:13,025] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:19:13,026] {logging_mixin.py:109} INFO - [2022-05-11 07:19:13,026] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:19:13,049] {logging_mixin.py:109} INFO - [2022-05-11 07:19:13,046] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:19:13,050] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:19:13,078] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.058 seconds
[2022-05-11 07:19:43,183] {processor.py:163} INFO - Started process (PID=32037) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:19:43,185] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:19:43,186] {logging_mixin.py:109} INFO - [2022-05-11 07:19:43,186] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:19:43,213] {logging_mixin.py:109} INFO - [2022-05-11 07:19:43,208] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:19:43,215] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:19:43,247] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.070 seconds
[2022-05-11 07:20:13,628] {processor.py:163} INFO - Started process (PID=32100) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:20:13,629] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:20:13,630] {logging_mixin.py:109} INFO - [2022-05-11 07:20:13,630] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:20:13,654] {logging_mixin.py:109} INFO - [2022-05-11 07:20:13,650] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:20:13,655] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:20:13,684] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.062 seconds
[2022-05-11 07:20:43,901] {processor.py:163} INFO - Started process (PID=32172) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:20:43,902] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:20:43,903] {logging_mixin.py:109} INFO - [2022-05-11 07:20:43,903] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:20:43,923] {logging_mixin.py:109} INFO - [2022-05-11 07:20:43,920] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:20:43,924] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:20:43,949] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.051 seconds
[2022-05-11 07:21:14,667] {processor.py:163} INFO - Started process (PID=32236) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:21:14,668] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:21:14,669] {logging_mixin.py:109} INFO - [2022-05-11 07:21:14,668] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:21:14,691] {logging_mixin.py:109} INFO - [2022-05-11 07:21:14,687] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:21:14,692] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:21:14,722] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.059 seconds
[2022-05-11 07:21:44,879] {processor.py:163} INFO - Started process (PID=32307) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:21:44,881] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:21:44,882] {logging_mixin.py:109} INFO - [2022-05-11 07:21:44,882] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:21:44,905] {logging_mixin.py:109} INFO - [2022-05-11 07:21:44,899] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:21:44,906] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:21:44,931] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.055 seconds
[2022-05-11 07:22:15,063] {processor.py:163} INFO - Started process (PID=32371) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:22:15,064] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:22:15,065] {logging_mixin.py:109} INFO - [2022-05-11 07:22:15,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:22:15,086] {logging_mixin.py:109} INFO - [2022-05-11 07:22:15,081] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:22:15,087] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:22:15,112] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.053 seconds
[2022-05-11 07:22:45,476] {processor.py:163} INFO - Started process (PID=32444) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:22:45,478] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:22:45,479] {logging_mixin.py:109} INFO - [2022-05-11 07:22:45,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:22:45,502] {logging_mixin.py:109} INFO - [2022-05-11 07:22:45,498] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:22:45,503] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:22:45,536] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.065 seconds
[2022-05-11 07:23:16,120] {processor.py:163} INFO - Started process (PID=32507) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:23:16,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:23:16,124] {logging_mixin.py:109} INFO - [2022-05-11 07:23:16,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:23:16,143] {logging_mixin.py:109} INFO - [2022-05-11 07:23:16,140] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:23:16,144] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:23:16,179] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.063 seconds
[2022-05-11 07:23:46,488] {processor.py:163} INFO - Started process (PID=32579) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:23:46,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:23:46,490] {logging_mixin.py:109} INFO - [2022-05-11 07:23:46,490] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:23:46,508] {logging_mixin.py:109} INFO - [2022-05-11 07:23:46,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:23:46,510] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:23:46,533] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.049 seconds
[2022-05-11 07:24:16,991] {processor.py:163} INFO - Started process (PID=32642) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:24:16,993] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:24:16,995] {logging_mixin.py:109} INFO - [2022-05-11 07:24:16,995] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:24:17,016] {logging_mixin.py:109} INFO - [2022-05-11 07:24:17,012] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:24:17,017] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:24:17,047] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.060 seconds
[2022-05-11 07:24:47,398] {processor.py:163} INFO - Started process (PID=32716) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:24:47,399] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:24:47,400] {logging_mixin.py:109} INFO - [2022-05-11 07:24:47,400] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:24:47,421] {logging_mixin.py:109} INFO - [2022-05-11 07:24:47,418] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:24:47,422] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:24:47,446] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.051 seconds
[2022-05-11 07:25:17,968] {processor.py:163} INFO - Started process (PID=311) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:25:17,970] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:25:17,971] {logging_mixin.py:109} INFO - [2022-05-11 07:25:17,971] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:25:17,987] {logging_mixin.py:109} INFO - [2022-05-11 07:25:17,984] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:25:17,989] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:25:18,018] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.053 seconds
[2022-05-11 07:25:48,294] {processor.py:163} INFO - Started process (PID=383) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:25:48,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:25:48,296] {logging_mixin.py:109} INFO - [2022-05-11 07:25:48,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:25:48,314] {logging_mixin.py:109} INFO - [2022-05-11 07:25:48,311] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:25:48,315] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:25:48,338] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.047 seconds
[2022-05-11 07:26:18,689] {processor.py:163} INFO - Started process (PID=447) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:26:18,690] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:26:18,691] {logging_mixin.py:109} INFO - [2022-05-11 07:26:18,691] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:26:18,706] {logging_mixin.py:109} INFO - [2022-05-11 07:26:18,704] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:26:18,707] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:26:18,727] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.041 seconds
[2022-05-11 07:26:49,093] {processor.py:163} INFO - Started process (PID=519) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:26:49,094] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:26:49,095] {logging_mixin.py:109} INFO - [2022-05-11 07:26:49,095] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:26:49,117] {logging_mixin.py:109} INFO - [2022-05-11 07:26:49,113] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:26:49,118] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:26:49,142] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.053 seconds
[2022-05-11 07:27:19,850] {processor.py:163} INFO - Started process (PID=592) to work on /opt/airflow/dags/ej10.py
[2022-05-11 07:27:19,852] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej10.py for tasks to queue
[2022-05-11 07:27:19,852] {logging_mixin.py:109} INFO - [2022-05-11 07:27:19,852] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej10.py
[2022-05-11 07:27:19,868] {logging_mixin.py:109} INFO - [2022-05-11 07:27:19,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej10.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej10.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:27:19,869] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej10.py
[2022-05-11 07:27:19,894] {processor.py:171} INFO - Processing /opt/airflow/dags/ej10.py took 0.047 seconds
