[2022-05-11 06:55:52,439] {processor.py:163} INFO - Started process (PID=28841) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:55:52,452] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:55:52,453] {logging_mixin.py:109} INFO - [2022-05-11 06:55:52,453] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:55:52,617] {logging_mixin.py:109} INFO - [2022-05-11 06:55:52,492] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:55:52,619] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:55:52,720] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.293 seconds
[2022-05-11 06:56:23,420] {processor.py:163} INFO - Started process (PID=28906) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:56:23,422] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:56:23,423] {logging_mixin.py:109} INFO - [2022-05-11 06:56:23,423] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:56:23,470] {logging_mixin.py:109} INFO - [2022-05-11 06:56:23,465] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:56:23,472] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:56:23,496] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-11 06:56:53,944] {processor.py:163} INFO - Started process (PID=28969) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:56:53,946] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:56:53,948] {logging_mixin.py:109} INFO - [2022-05-11 06:56:53,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:56:53,997] {logging_mixin.py:109} INFO - [2022-05-11 06:56:53,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:56:54,000] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:56:54,036] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.095 seconds
[2022-05-11 06:57:24,440] {processor.py:163} INFO - Started process (PID=29042) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:57:24,442] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:57:24,443] {logging_mixin.py:109} INFO - [2022-05-11 06:57:24,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:57:24,489] {logging_mixin.py:109} INFO - [2022-05-11 06:57:24,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:57:24,492] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:57:24,522] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-11 06:57:54,658] {processor.py:163} INFO - Started process (PID=29105) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:57:54,660] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:57:54,661] {logging_mixin.py:109} INFO - [2022-05-11 06:57:54,661] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:57:54,711] {logging_mixin.py:109} INFO - [2022-05-11 06:57:54,702] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:57:54,714] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:57:54,741] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-11 06:58:25,195] {processor.py:163} INFO - Started process (PID=29178) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:58:25,196] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:58:25,197] {logging_mixin.py:109} INFO - [2022-05-11 06:58:25,197] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:58:25,225] {logging_mixin.py:109} INFO - [2022-05-11 06:58:25,220] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:58:25,227] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:58:25,248] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.056 seconds
[2022-05-11 06:58:55,440] {processor.py:163} INFO - Started process (PID=29240) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:58:55,442] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:58:55,443] {logging_mixin.py:109} INFO - [2022-05-11 06:58:55,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:58:55,477] {logging_mixin.py:109} INFO - [2022-05-11 06:58:55,471] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:58:55,479] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:58:55,501] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.065 seconds
[2022-05-11 06:59:25,612] {processor.py:163} INFO - Started process (PID=29313) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:59:25,614] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:59:25,616] {logging_mixin.py:109} INFO - [2022-05-11 06:59:25,615] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:59:25,658] {logging_mixin.py:109} INFO - [2022-05-11 06:59:25,651] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:59:25,661] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:59:25,686] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-11 06:59:55,755] {processor.py:163} INFO - Started process (PID=29376) to work on /opt/airflow/dags/ej4.py
[2022-05-11 06:59:55,757] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 06:59:55,758] {logging_mixin.py:109} INFO - [2022-05-11 06:59:55,757] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 06:59:55,783] {logging_mixin.py:109} INFO - [2022-05-11 06:59:55,780] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 06:59:55,785] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 06:59:55,807] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-11 07:00:26,238] {processor.py:163} INFO - Started process (PID=29450) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:00:26,240] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:00:26,242] {logging_mixin.py:109} INFO - [2022-05-11 07:00:26,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:00:26,282] {logging_mixin.py:109} INFO - [2022-05-11 07:00:26,273] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:00:26,285] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:00:26,311] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.078 seconds
[2022-05-11 07:00:56,914] {processor.py:163} INFO - Started process (PID=29521) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:00:56,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:00:56,917] {logging_mixin.py:109} INFO - [2022-05-11 07:00:56,916] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:00:56,952] {logging_mixin.py:109} INFO - [2022-05-11 07:00:56,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:00:56,955] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:00:56,982] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.071 seconds
[2022-05-11 07:01:27,602] {processor.py:163} INFO - Started process (PID=29586) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:01:27,603] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:01:27,604] {logging_mixin.py:109} INFO - [2022-05-11 07:01:27,604] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:01:27,641] {logging_mixin.py:109} INFO - [2022-05-11 07:01:27,634] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:01:27,644] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:01:27,670] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.072 seconds
[2022-05-11 07:01:57,874] {processor.py:163} INFO - Started process (PID=29659) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:01:57,875] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:01:57,876] {logging_mixin.py:109} INFO - [2022-05-11 07:01:57,876] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:01:57,902] {logging_mixin.py:109} INFO - [2022-05-11 07:01:57,898] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:01:57,903] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:01:57,925] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.056 seconds
[2022-05-11 07:02:28,275] {processor.py:163} INFO - Started process (PID=29723) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:02:28,278] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:02:28,279] {logging_mixin.py:109} INFO - [2022-05-11 07:02:28,279] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:02:28,312] {logging_mixin.py:109} INFO - [2022-05-11 07:02:28,307] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:02:28,314] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:02:28,350] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.081 seconds
[2022-05-11 07:02:59,011] {processor.py:163} INFO - Started process (PID=29796) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:02:59,013] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:02:59,014] {logging_mixin.py:109} INFO - [2022-05-11 07:02:59,014] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:02:59,039] {logging_mixin.py:109} INFO - [2022-05-11 07:02:59,033] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:02:59,041] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:02:59,067] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.059 seconds
[2022-05-11 07:03:29,455] {processor.py:163} INFO - Started process (PID=29858) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:03:29,458] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:03:29,459] {logging_mixin.py:109} INFO - [2022-05-11 07:03:29,459] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:03:29,487] {logging_mixin.py:109} INFO - [2022-05-11 07:03:29,483] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:03:29,489] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:03:29,513] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-11 07:04:00,266] {processor.py:163} INFO - Started process (PID=29930) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:04:00,268] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:04:00,269] {logging_mixin.py:109} INFO - [2022-05-11 07:04:00,269] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:04:00,305] {logging_mixin.py:109} INFO - [2022-05-11 07:04:00,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:04:00,308] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:04:00,333] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.069 seconds
[2022-05-11 07:04:30,784] {processor.py:163} INFO - Started process (PID=29993) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:04:30,786] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:04:30,787] {logging_mixin.py:109} INFO - [2022-05-11 07:04:30,787] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:04:30,824] {logging_mixin.py:109} INFO - [2022-05-11 07:04:30,816] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:04:30,826] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:04:30,855] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-11 07:05:01,286] {processor.py:163} INFO - Started process (PID=30067) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:05:01,288] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:05:01,289] {logging_mixin.py:109} INFO - [2022-05-11 07:05:01,289] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:05:01,319] {logging_mixin.py:109} INFO - [2022-05-11 07:05:01,311] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:05:01,322] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:05:01,344] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-11 07:05:31,758] {processor.py:163} INFO - Started process (PID=30131) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:05:31,759] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:05:31,760] {logging_mixin.py:109} INFO - [2022-05-11 07:05:31,760] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:05:31,800] {logging_mixin.py:109} INFO - [2022-05-11 07:05:31,791] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:05:31,803] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:05:31,829] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-11 07:06:02,140] {processor.py:163} INFO - Started process (PID=30204) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:06:02,142] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:06:02,142] {logging_mixin.py:109} INFO - [2022-05-11 07:06:02,142] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:06:02,178] {logging_mixin.py:109} INFO - [2022-05-11 07:06:02,171] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:06:02,181] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:06:02,205] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.068 seconds
[2022-05-11 07:06:32,679] {processor.py:163} INFO - Started process (PID=30275) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:06:32,681] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:06:32,682] {logging_mixin.py:109} INFO - [2022-05-11 07:06:32,681] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:06:32,713] {logging_mixin.py:109} INFO - [2022-05-11 07:06:32,707] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:06:32,716] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:06:32,737] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-11 07:07:03,211] {processor.py:163} INFO - Started process (PID=30337) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:07:03,212] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:07:03,214] {logging_mixin.py:109} INFO - [2022-05-11 07:07:03,214] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:07:03,259] {logging_mixin.py:109} INFO - [2022-05-11 07:07:03,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:07:03,261] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:07:03,288] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.081 seconds
[2022-05-11 07:07:33,602] {processor.py:163} INFO - Started process (PID=30410) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:07:33,604] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:07:33,605] {logging_mixin.py:109} INFO - [2022-05-11 07:07:33,605] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:07:33,637] {logging_mixin.py:109} INFO - [2022-05-11 07:07:33,631] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:07:33,639] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:07:33,666] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.068 seconds
[2022-05-11 07:08:03,808] {processor.py:163} INFO - Started process (PID=30472) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:08:03,810] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:08:03,811] {logging_mixin.py:109} INFO - [2022-05-11 07:08:03,811] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:08:03,843] {logging_mixin.py:109} INFO - [2022-05-11 07:08:03,837] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:08:03,845] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:08:03,869] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.065 seconds
[2022-05-11 07:08:34,302] {processor.py:163} INFO - Started process (PID=30544) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:08:34,304] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:08:34,305] {logging_mixin.py:109} INFO - [2022-05-11 07:08:34,304] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:08:34,337] {logging_mixin.py:109} INFO - [2022-05-11 07:08:34,332] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:08:34,338] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:08:34,367] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.068 seconds
[2022-05-11 07:09:04,559] {processor.py:163} INFO - Started process (PID=30607) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:09:04,561] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:09:04,562] {logging_mixin.py:109} INFO - [2022-05-11 07:09:04,562] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:09:04,603] {logging_mixin.py:109} INFO - [2022-05-11 07:09:04,594] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:09:04,606] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:09:04,635] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-11 07:09:35,196] {processor.py:163} INFO - Started process (PID=30679) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:09:35,198] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:09:35,199] {logging_mixin.py:109} INFO - [2022-05-11 07:09:35,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:09:35,247] {logging_mixin.py:109} INFO - [2022-05-11 07:09:35,238] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:09:35,250] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:09:35,276] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.084 seconds
[2022-05-11 07:10:05,593] {processor.py:163} INFO - Started process (PID=30741) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:10:05,595] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:10:05,596] {logging_mixin.py:109} INFO - [2022-05-11 07:10:05,596] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:10:05,635] {logging_mixin.py:109} INFO - [2022-05-11 07:10:05,627] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:10:05,639] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:10:05,668] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.078 seconds
[2022-05-11 07:10:36,284] {processor.py:163} INFO - Started process (PID=30814) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:10:36,286] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:10:36,287] {logging_mixin.py:109} INFO - [2022-05-11 07:10:36,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:10:36,329] {logging_mixin.py:109} INFO - [2022-05-11 07:10:36,320] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:10:36,333] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:10:36,376] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.096 seconds
[2022-05-11 07:11:06,913] {processor.py:163} INFO - Started process (PID=30885) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:11:06,915] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:11:06,916] {logging_mixin.py:109} INFO - [2022-05-11 07:11:06,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:11:06,951] {logging_mixin.py:109} INFO - [2022-05-11 07:11:06,942] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:11:06,954] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:11:06,981] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.071 seconds
[2022-05-11 07:11:38,302] {processor.py:163} INFO - Started process (PID=30950) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:11:38,304] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:11:38,305] {logging_mixin.py:109} INFO - [2022-05-11 07:11:38,305] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:11:38,387] {logging_mixin.py:109} INFO - [2022-05-11 07:11:38,377] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:11:38,389] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:11:38,437] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.139 seconds
[2022-05-11 07:12:09,177] {processor.py:163} INFO - Started process (PID=31023) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:12:09,178] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:12:09,179] {logging_mixin.py:109} INFO - [2022-05-11 07:12:09,179] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:12:09,206] {logging_mixin.py:109} INFO - [2022-05-11 07:12:09,202] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:12:09,207] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:12:09,232] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.059 seconds
[2022-05-11 07:12:40,114] {processor.py:163} INFO - Started process (PID=31087) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:12:40,116] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:12:40,117] {logging_mixin.py:109} INFO - [2022-05-11 07:12:40,117] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:12:40,144] {logging_mixin.py:109} INFO - [2022-05-11 07:12:40,140] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:12:40,145] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:12:40,168] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.058 seconds
[2022-05-11 07:13:10,408] {processor.py:163} INFO - Started process (PID=31160) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:13:10,409] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:13:10,411] {logging_mixin.py:109} INFO - [2022-05-11 07:13:10,411] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:13:10,440] {logging_mixin.py:109} INFO - [2022-05-11 07:13:10,436] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:13:10,443] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:13:10,465] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-11 07:13:40,688] {processor.py:163} INFO - Started process (PID=31224) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:13:40,690] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:13:40,691] {logging_mixin.py:109} INFO - [2022-05-11 07:13:40,691] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:13:40,715] {logging_mixin.py:109} INFO - [2022-05-11 07:13:40,711] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:13:40,716] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:13:40,740] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-11 07:14:11,075] {processor.py:163} INFO - Started process (PID=31296) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:14:11,078] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:14:11,079] {logging_mixin.py:109} INFO - [2022-05-11 07:14:11,079] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:14:11,105] {logging_mixin.py:109} INFO - [2022-05-11 07:14:11,101] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:14:11,107] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:14:11,137] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-11 07:14:41,734] {processor.py:163} INFO - Started process (PID=31359) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:14:41,736] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:14:41,737] {logging_mixin.py:109} INFO - [2022-05-11 07:14:41,737] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:14:41,760] {logging_mixin.py:109} INFO - [2022-05-11 07:14:41,757] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:14:41,761] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:14:41,790] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-11 07:15:11,882] {processor.py:163} INFO - Started process (PID=31432) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:15:11,883] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:15:11,884] {logging_mixin.py:109} INFO - [2022-05-11 07:15:11,884] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:15:11,908] {logging_mixin.py:109} INFO - [2022-05-11 07:15:11,905] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:15:11,910] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:15:11,930] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.052 seconds
[2022-05-11 07:15:42,096] {processor.py:163} INFO - Started process (PID=31497) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:15:42,097] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:15:42,099] {logging_mixin.py:109} INFO - [2022-05-11 07:15:42,098] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:15:42,128] {logging_mixin.py:109} INFO - [2022-05-11 07:15:42,124] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:15:42,129] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:15:42,159] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.067 seconds
[2022-05-11 07:16:12,645] {processor.py:163} INFO - Started process (PID=31571) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:16:12,646] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:16:12,647] {logging_mixin.py:109} INFO - [2022-05-11 07:16:12,647] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:16:12,671] {logging_mixin.py:109} INFO - [2022-05-11 07:16:12,666] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:16:12,673] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:16:12,705] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.064 seconds
[2022-05-11 07:16:43,070] {processor.py:163} INFO - Started process (PID=31644) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:16:43,072] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:16:43,074] {logging_mixin.py:109} INFO - [2022-05-11 07:16:43,073] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:16:43,109] {logging_mixin.py:109} INFO - [2022-05-11 07:16:43,103] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:16:43,111] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:16:43,148] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.081 seconds
[2022-05-11 07:17:13,653] {processor.py:163} INFO - Started process (PID=31706) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:17:13,656] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:17:13,658] {logging_mixin.py:109} INFO - [2022-05-11 07:17:13,658] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:17:13,692] {logging_mixin.py:109} INFO - [2022-05-11 07:17:13,686] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:17:13,695] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:17:13,735] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.090 seconds
[2022-05-11 07:17:44,119] {processor.py:163} INFO - Started process (PID=31770) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:17:44,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:17:44,121] {logging_mixin.py:109} INFO - [2022-05-11 07:17:44,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:17:44,152] {logging_mixin.py:109} INFO - [2022-05-11 07:17:44,147] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:17:44,154] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:17:44,187] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.072 seconds
[2022-05-11 07:18:14,834] {processor.py:163} INFO - Started process (PID=31843) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:18:14,836] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:18:14,838] {logging_mixin.py:109} INFO - [2022-05-11 07:18:14,838] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:18:14,865] {logging_mixin.py:109} INFO - [2022-05-11 07:18:14,860] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:18:14,866] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:18:14,903] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.074 seconds
[2022-05-11 07:18:44,991] {processor.py:163} INFO - Started process (PID=31905) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:18:44,993] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:18:44,994] {logging_mixin.py:109} INFO - [2022-05-11 07:18:44,994] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:18:45,021] {logging_mixin.py:109} INFO - [2022-05-11 07:18:45,018] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:18:45,023] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:18:45,050] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.065 seconds
[2022-05-11 07:19:15,226] {processor.py:163} INFO - Started process (PID=31978) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:19:15,228] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:19:15,230] {logging_mixin.py:109} INFO - [2022-05-11 07:19:15,229] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:19:15,276] {logging_mixin.py:109} INFO - [2022-05-11 07:19:15,267] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:19:15,278] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:19:15,395] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.174 seconds
[2022-05-11 07:19:45,449] {processor.py:163} INFO - Started process (PID=32040) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:19:45,451] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:19:45,452] {logging_mixin.py:109} INFO - [2022-05-11 07:19:45,452] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:19:45,477] {logging_mixin.py:109} INFO - [2022-05-11 07:19:45,472] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:19:45,478] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:19:45,506] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-11 07:20:15,754] {processor.py:163} INFO - Started process (PID=32112) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:20:15,756] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:20:15,757] {logging_mixin.py:109} INFO - [2022-05-11 07:20:15,757] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:20:15,783] {logging_mixin.py:109} INFO - [2022-05-11 07:20:15,778] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:20:15,784] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:20:15,807] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.056 seconds
[2022-05-11 07:20:46,045] {processor.py:163} INFO - Started process (PID=32175) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:20:46,046] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:20:46,047] {logging_mixin.py:109} INFO - [2022-05-11 07:20:46,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:20:46,070] {logging_mixin.py:109} INFO - [2022-05-11 07:20:46,066] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:20:46,071] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:20:46,094] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.053 seconds
[2022-05-11 07:21:16,829] {processor.py:163} INFO - Started process (PID=32248) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:21:16,830] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:21:16,832] {logging_mixin.py:109} INFO - [2022-05-11 07:21:16,831] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:21:16,859] {logging_mixin.py:109} INFO - [2022-05-11 07:21:16,855] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:21:16,860] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:21:16,885] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.060 seconds
[2022-05-11 07:21:47,033] {processor.py:163} INFO - Started process (PID=32310) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:21:47,034] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:21:47,035] {logging_mixin.py:109} INFO - [2022-05-11 07:21:47,035] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:21:47,054] {logging_mixin.py:109} INFO - [2022-05-11 07:21:47,051] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:21:47,055] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:21:47,080] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.050 seconds
[2022-05-11 07:22:17,183] {processor.py:163} INFO - Started process (PID=32382) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:22:17,184] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:22:17,185] {logging_mixin.py:109} INFO - [2022-05-11 07:22:17,185] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:22:17,210] {logging_mixin.py:109} INFO - [2022-05-11 07:22:17,206] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:22:17,211] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:22:17,239] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-11 07:22:47,592] {processor.py:163} INFO - Started process (PID=32447) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:22:47,593] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:22:47,594] {logging_mixin.py:109} INFO - [2022-05-11 07:22:47,594] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:22:47,627] {logging_mixin.py:109} INFO - [2022-05-11 07:22:47,623] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:22:47,628] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:22:47,659] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.072 seconds
[2022-05-11 07:23:18,269] {processor.py:163} INFO - Started process (PID=32510) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:23:18,270] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:23:18,271] {logging_mixin.py:109} INFO - [2022-05-11 07:23:18,271] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:23:18,292] {logging_mixin.py:109} INFO - [2022-05-11 07:23:18,288] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:23:18,293] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:23:18,323] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.057 seconds
[2022-05-11 07:23:48,609] {processor.py:163} INFO - Started process (PID=32582) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:23:48,611] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:23:48,612] {logging_mixin.py:109} INFO - [2022-05-11 07:23:48,612] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:23:48,643] {logging_mixin.py:109} INFO - [2022-05-11 07:23:48,638] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:23:48,645] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:23:48,671] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.067 seconds
[2022-05-11 07:24:19,123] {processor.py:163} INFO - Started process (PID=32655) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:24:19,124] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:24:19,125] {logging_mixin.py:109} INFO - [2022-05-11 07:24:19,125] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:24:19,154] {logging_mixin.py:109} INFO - [2022-05-11 07:24:19,148] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:24:19,155] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:24:19,183] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.067 seconds
[2022-05-11 07:24:49,516] {processor.py:163} INFO - Started process (PID=32719) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:24:49,517] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:24:49,518] {logging_mixin.py:109} INFO - [2022-05-11 07:24:49,518] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:24:49,548] {logging_mixin.py:109} INFO - [2022-05-11 07:24:49,543] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:24:49,551] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:24:49,577] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-11 07:25:20,102] {processor.py:163} INFO - Started process (PID=321) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:25:20,103] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:25:20,104] {logging_mixin.py:109} INFO - [2022-05-11 07:25:20,104] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:25:20,131] {logging_mixin.py:109} INFO - [2022-05-11 07:25:20,127] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:25:20,133] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:25:20,160] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-11 07:25:50,552] {processor.py:163} INFO - Started process (PID=386) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:25:50,554] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:25:50,556] {logging_mixin.py:109} INFO - [2022-05-11 07:25:50,555] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:25:50,578] {logging_mixin.py:109} INFO - [2022-05-11 07:25:50,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:25:50,579] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:25:50,601] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.051 seconds
[2022-05-11 07:26:20,806] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:26:20,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:26:20,808] {logging_mixin.py:109} INFO - [2022-05-11 07:26:20,808] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:26:20,828] {logging_mixin.py:109} INFO - [2022-05-11 07:26:20,825] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:26:20,829] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:26:20,847] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.044 seconds
[2022-05-11 07:26:51,549] {processor.py:163} INFO - Started process (PID=524) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:26:51,551] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:26:51,552] {logging_mixin.py:109} INFO - [2022-05-11 07:26:51,551] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:26:51,573] {logging_mixin.py:109} INFO - [2022-05-11 07:26:51,570] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:26:51,574] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:26:51,594] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.048 seconds
[2022-05-11 07:27:22,425] {processor.py:163} INFO - Started process (PID=597) to work on /opt/airflow/dags/ej4.py
[2022-05-11 07:27:22,427] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-11 07:27:22,428] {logging_mixin.py:109} INFO - [2022-05-11 07:27:22,428] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-11 07:27:22,463] {logging_mixin.py:109} INFO - [2022-05-11 07:27:22,459] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-11 07:27:22,464] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-11 07:27:22,488] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
