[2022-05-07 07:01:46,113] {processor.py:163} INFO - Started process (PID=8753) to work on /opt/airflow/dags/ej4.py
[2022-05-07 07:01:46,116] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-07 07:01:46,119] {logging_mixin.py:109} INFO - [2022-05-07 07:01:46,118] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-07 07:01:46,233] {logging_mixin.py:109} INFO - [2022-05-07 07:01:46,195] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-07 07:01:46,257] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-07 07:01:46,370] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.262 seconds
