[2022-05-17 06:58:11,421] {processor.py:163} INFO - Started process (PID=10482) to work on /opt/airflow/dags/ej4.py
[2022-05-17 06:58:11,432] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 06:58:11,438] {logging_mixin.py:109} INFO - [2022-05-17 06:58:11,438] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 06:58:11,481] {logging_mixin.py:109} INFO - [2022-05-17 06:58:11,477] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 06:58:11,483] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 06:58:11,520] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.103 seconds
[2022-05-17 06:58:41,742] {processor.py:163} INFO - Started process (PID=10544) to work on /opt/airflow/dags/ej4.py
[2022-05-17 06:58:41,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 06:58:41,743] {logging_mixin.py:109} INFO - [2022-05-17 06:58:41,743] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 06:58:41,765] {logging_mixin.py:109} INFO - [2022-05-17 06:58:41,762] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 06:58:41,766] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 06:58:41,785] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.046 seconds
[2022-05-17 06:59:11,860] {processor.py:163} INFO - Started process (PID=10617) to work on /opt/airflow/dags/ej4.py
[2022-05-17 06:59:11,861] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 06:59:11,862] {logging_mixin.py:109} INFO - [2022-05-17 06:59:11,862] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 06:59:11,885] {logging_mixin.py:109} INFO - [2022-05-17 06:59:11,881] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 06:59:11,887] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 06:59:11,908] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.051 seconds
[2022-05-17 06:59:42,067] {processor.py:163} INFO - Started process (PID=10680) to work on /opt/airflow/dags/ej4.py
[2022-05-17 06:59:42,069] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 06:59:42,070] {logging_mixin.py:109} INFO - [2022-05-17 06:59:42,069] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 06:59:42,101] {logging_mixin.py:109} INFO - [2022-05-17 06:59:42,098] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 06:59:42,102] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 06:59:42,125] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-17 07:00:12,543] {processor.py:163} INFO - Started process (PID=10753) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:00:12,544] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:00:12,545] {logging_mixin.py:109} INFO - [2022-05-17 07:00:12,545] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:00:12,564] {logging_mixin.py:109} INFO - [2022-05-17 07:00:12,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:00:12,565] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:00:12,586] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.046 seconds
[2022-05-17 07:00:43,429] {processor.py:163} INFO - Started process (PID=10816) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:00:43,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:00:43,431] {logging_mixin.py:109} INFO - [2022-05-17 07:00:43,431] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:00:43,446] {logging_mixin.py:109} INFO - [2022-05-17 07:00:43,444] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:00:43,447] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:00:43,467] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.041 seconds
[2022-05-17 07:01:14,116] {processor.py:163} INFO - Started process (PID=10889) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:01:14,117] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:01:14,118] {logging_mixin.py:109} INFO - [2022-05-17 07:01:14,118] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:01:14,134] {logging_mixin.py:109} INFO - [2022-05-17 07:01:14,131] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:01:14,135] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:01:14,157] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.043 seconds
[2022-05-17 07:01:44,885] {processor.py:163} INFO - Started process (PID=10951) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:01:44,886] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:01:44,887] {logging_mixin.py:109} INFO - [2022-05-17 07:01:44,887] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:01:44,902] {logging_mixin.py:109} INFO - [2022-05-17 07:01:44,900] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:01:44,903] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:01:44,921] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.039 seconds
[2022-05-17 07:02:15,449] {processor.py:163} INFO - Started process (PID=11025) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:02:15,451] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:02:15,451] {logging_mixin.py:109} INFO - [2022-05-17 07:02:15,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:02:15,468] {logging_mixin.py:109} INFO - [2022-05-17 07:02:15,465] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:02:15,469] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:02:15,490] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.043 seconds
[2022-05-17 07:02:45,646] {processor.py:163} INFO - Started process (PID=11098) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:02:45,648] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:02:45,648] {logging_mixin.py:109} INFO - [2022-05-17 07:02:45,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:02:45,666] {logging_mixin.py:109} INFO - [2022-05-17 07:02:45,663] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:02:45,668] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:02:45,688] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.046 seconds
[2022-05-17 07:03:15,779] {processor.py:163} INFO - Started process (PID=11162) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:03:15,780] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:03:15,781] {logging_mixin.py:109} INFO - [2022-05-17 07:03:15,781] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:03:15,798] {logging_mixin.py:109} INFO - [2022-05-17 07:03:15,795] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:03:15,799] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:03:15,817] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.040 seconds
[2022-05-17 07:03:46,471] {processor.py:163} INFO - Started process (PID=11236) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:03:46,472] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:03:46,473] {logging_mixin.py:109} INFO - [2022-05-17 07:03:46,473] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:03:46,489] {logging_mixin.py:109} INFO - [2022-05-17 07:03:46,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:03:46,490] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:03:46,510] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.042 seconds
[2022-05-17 07:04:17,220] {processor.py:163} INFO - Started process (PID=11300) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:04:17,221] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:04:17,222] {logging_mixin.py:109} INFO - [2022-05-17 07:04:17,221] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:04:17,239] {logging_mixin.py:109} INFO - [2022-05-17 07:04:17,236] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:04:17,240] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:04:17,261] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.045 seconds
[2022-05-17 07:04:47,996] {processor.py:163} INFO - Started process (PID=11371) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:04:47,997] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:04:47,998] {logging_mixin.py:109} INFO - [2022-05-17 07:04:47,998] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:04:48,016] {logging_mixin.py:109} INFO - [2022-05-17 07:04:48,013] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:04:48,017] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:04:48,039] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.047 seconds
[2022-05-17 07:05:18,817] {processor.py:163} INFO - Started process (PID=11444) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:05:18,818] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:05:18,819] {logging_mixin.py:109} INFO - [2022-05-17 07:05:18,819] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:05:18,835] {logging_mixin.py:109} INFO - [2022-05-17 07:05:18,832] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:05:18,836] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:05:18,855] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.040 seconds
[2022-05-17 07:05:49,545] {processor.py:163} INFO - Started process (PID=11507) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:05:49,547] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:05:49,548] {logging_mixin.py:109} INFO - [2022-05-17 07:05:49,548] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:05:49,568] {logging_mixin.py:109} INFO - [2022-05-17 07:05:49,564] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:05:49,569] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:05:49,597] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.054 seconds
[2022-05-17 07:06:20,305] {processor.py:163} INFO - Started process (PID=11580) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:06:20,306] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:06:20,306] {logging_mixin.py:109} INFO - [2022-05-17 07:06:20,306] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:06:20,329] {logging_mixin.py:109} INFO - [2022-05-17 07:06:20,326] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:06:20,332] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:06:20,357] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-17 07:06:50,664] {processor.py:163} INFO - Started process (PID=11643) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:06:50,667] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:06:50,668] {logging_mixin.py:109} INFO - [2022-05-17 07:06:50,668] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:06:50,700] {logging_mixin.py:109} INFO - [2022-05-17 07:06:50,694] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:06:50,702] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:06:50,769] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.110 seconds
[2022-05-17 07:07:21,245] {processor.py:163} INFO - Started process (PID=11717) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:07:21,247] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:07:21,248] {logging_mixin.py:109} INFO - [2022-05-17 07:07:21,248] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:07:21,296] {logging_mixin.py:109} INFO - [2022-05-17 07:07:21,282] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:07:21,298] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:07:21,339] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.099 seconds
[2022-05-17 07:07:51,402] {processor.py:163} INFO - Started process (PID=11781) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:07:51,403] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:07:51,404] {logging_mixin.py:109} INFO - [2022-05-17 07:07:51,404] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:07:51,423] {logging_mixin.py:109} INFO - [2022-05-17 07:07:51,420] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:07:51,424] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:07:51,445] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.047 seconds
[2022-05-17 07:08:21,695] {processor.py:163} INFO - Started process (PID=11843) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:08:21,697] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:08:21,698] {logging_mixin.py:109} INFO - [2022-05-17 07:08:21,698] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:08:21,730] {logging_mixin.py:109} INFO - [2022-05-17 07:08:21,725] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:08:21,732] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:08:21,765] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-17 07:08:51,855] {processor.py:163} INFO - Started process (PID=11906) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:08:51,859] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:08:51,860] {logging_mixin.py:109} INFO - [2022-05-17 07:08:51,860] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:08:51,887] {logging_mixin.py:109} INFO - [2022-05-17 07:08:51,882] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:08:51,889] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:08:51,918] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-17 07:09:22,487] {processor.py:163} INFO - Started process (PID=11978) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:09:22,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:09:22,491] {logging_mixin.py:109} INFO - [2022-05-17 07:09:22,490] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:09:22,545] {logging_mixin.py:109} INFO - [2022-05-17 07:09:22,536] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:09:22,547] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:09:22,600] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.121 seconds
[2022-05-17 07:09:53,552] {processor.py:163} INFO - Started process (PID=12042) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:09:53,554] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:09:53,555] {logging_mixin.py:109} INFO - [2022-05-17 07:09:53,555] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:09:53,596] {logging_mixin.py:109} INFO - [2022-05-17 07:09:53,588] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:09:53,597] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:09:53,632] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.087 seconds
[2022-05-17 07:10:24,239] {processor.py:163} INFO - Started process (PID=12104) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:10:24,240] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:10:24,241] {logging_mixin.py:109} INFO - [2022-05-17 07:10:24,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:10:24,266] {logging_mixin.py:109} INFO - [2022-05-17 07:10:24,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:10:24,267] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:10:24,296] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-17 07:10:54,629] {processor.py:163} INFO - Started process (PID=12178) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:10:54,632] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:10:54,633] {logging_mixin.py:109} INFO - [2022-05-17 07:10:54,632] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:10:54,664] {logging_mixin.py:109} INFO - [2022-05-17 07:10:54,660] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:10:54,665] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:10:54,699] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.074 seconds
[2022-05-17 07:11:24,834] {processor.py:163} INFO - Started process (PID=12246) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:11:24,836] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:11:24,837] {logging_mixin.py:109} INFO - [2022-05-17 07:11:24,837] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:11:24,863] {logging_mixin.py:109} INFO - [2022-05-17 07:11:24,859] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:11:24,865] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:11:24,893] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.064 seconds
[2022-05-17 07:11:55,417] {processor.py:163} INFO - Started process (PID=12308) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:11:55,419] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:11:55,420] {logging_mixin.py:109} INFO - [2022-05-17 07:11:55,420] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:11:55,465] {logging_mixin.py:109} INFO - [2022-05-17 07:11:55,450] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:11:55,467] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:11:55,508] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.095 seconds
[2022-05-17 07:12:49,385] {processor.py:163} INFO - Started process (PID=12371) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:12:49,389] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:12:49,390] {logging_mixin.py:109} INFO - [2022-05-17 07:12:49,390] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:12:49,443] {logging_mixin.py:109} INFO - [2022-05-17 07:12:49,423] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:12:49,445] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:12:49,483] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.103 seconds
[2022-05-17 07:13:19,761] {processor.py:163} INFO - Started process (PID=12435) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:13:19,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:13:19,764] {logging_mixin.py:109} INFO - [2022-05-17 07:13:19,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:13:19,783] {logging_mixin.py:109} INFO - [2022-05-17 07:13:19,780] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:13:19,784] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:13:19,811] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.053 seconds
[2022-05-17 07:13:50,820] {processor.py:163} INFO - Started process (PID=12510) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:13:50,822] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:13:50,822] {logging_mixin.py:109} INFO - [2022-05-17 07:13:50,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:13:50,842] {logging_mixin.py:109} INFO - [2022-05-17 07:13:50,839] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:13:50,843] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:13:50,917] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.100 seconds
[2022-05-17 07:14:21,085] {processor.py:163} INFO - Started process (PID=12576) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:14:21,086] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:14:21,086] {logging_mixin.py:109} INFO - [2022-05-17 07:14:21,086] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:14:21,104] {logging_mixin.py:109} INFO - [2022-05-17 07:14:21,101] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:14:21,105] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:14:21,127] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.045 seconds
[2022-05-17 07:14:52,108] {processor.py:163} INFO - Started process (PID=12649) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:14:52,110] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:14:52,111] {logging_mixin.py:109} INFO - [2022-05-17 07:14:52,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:14:52,130] {logging_mixin.py:109} INFO - [2022-05-17 07:14:52,126] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:14:52,131] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:14:52,153] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.048 seconds
[2022-05-17 07:15:22,912] {processor.py:163} INFO - Started process (PID=12713) to work on /opt/airflow/dags/ej4.py
[2022-05-17 07:15:22,914] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-17 07:15:22,915] {logging_mixin.py:109} INFO - [2022-05-17 07:15:22,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-17 07:15:22,937] {logging_mixin.py:109} INFO - [2022-05-17 07:15:22,933] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-17 07:15:22,938] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-17 07:15:22,961] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.052 seconds
