[2022-05-17 06:58:11,221] {processor.py:163} INFO - Started process (PID=10481) to work on /opt/airflow/dags/ej8.py
[2022-05-17 06:58:11,223] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 06:58:11,224] {logging_mixin.py:109} INFO - [2022-05-17 06:58:11,224] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 06:58:11,255] {logging_mixin.py:109} INFO - [2022-05-17 06:58:11,250] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 06:58:11,257] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 06:58:11,313] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.099 seconds
[2022-05-17 06:58:41,659] {processor.py:163} INFO - Started process (PID=10543) to work on /opt/airflow/dags/ej8.py
[2022-05-17 06:58:41,660] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 06:58:41,661] {logging_mixin.py:109} INFO - [2022-05-17 06:58:41,661] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 06:58:41,680] {logging_mixin.py:109} INFO - [2022-05-17 06:58:41,677] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 06:58:41,682] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 06:58:41,705] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.050 seconds
[2022-05-17 06:59:11,820] {processor.py:163} INFO - Started process (PID=10616) to work on /opt/airflow/dags/ej8.py
[2022-05-17 06:59:11,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 06:59:11,822] {logging_mixin.py:109} INFO - [2022-05-17 06:59:11,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 06:59:11,844] {logging_mixin.py:109} INFO - [2022-05-17 06:59:11,841] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 06:59:11,845] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 06:59:11,867] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.050 seconds
[2022-05-17 06:59:42,035] {processor.py:163} INFO - Started process (PID=10679) to work on /opt/airflow/dags/ej8.py
[2022-05-17 06:59:42,037] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 06:59:42,038] {logging_mixin.py:109} INFO - [2022-05-17 06:59:42,038] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 06:59:42,089] {logging_mixin.py:109} INFO - [2022-05-17 06:59:42,086] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 06:59:42,090] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 06:59:42,112] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.081 seconds
[2022-05-17 07:00:12,533] {processor.py:163} INFO - Started process (PID=10752) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:00:12,534] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:00:12,535] {logging_mixin.py:109} INFO - [2022-05-17 07:00:12,535] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:00:12,554] {logging_mixin.py:109} INFO - [2022-05-17 07:00:12,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:00:12,555] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:00:12,577] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.047 seconds
[2022-05-17 07:00:43,364] {processor.py:163} INFO - Started process (PID=10815) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:00:43,365] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:00:43,366] {logging_mixin.py:109} INFO - [2022-05-17 07:00:43,365] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:00:43,383] {logging_mixin.py:109} INFO - [2022-05-17 07:00:43,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:00:43,384] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:00:43,405] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.044 seconds
[2022-05-17 07:01:14,052] {processor.py:163} INFO - Started process (PID=10888) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:01:14,054] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:01:14,054] {logging_mixin.py:109} INFO - [2022-05-17 07:01:14,054] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:01:14,070] {logging_mixin.py:109} INFO - [2022-05-17 07:01:14,067] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:01:14,071] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:01:14,090] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.041 seconds
[2022-05-17 07:01:44,825] {processor.py:163} INFO - Started process (PID=10950) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:01:44,826] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:01:44,827] {logging_mixin.py:109} INFO - [2022-05-17 07:01:44,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:01:44,841] {logging_mixin.py:109} INFO - [2022-05-17 07:01:44,839] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:01:44,842] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:01:44,861] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.038 seconds
[2022-05-17 07:02:15,448] {processor.py:163} INFO - Started process (PID=11024) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:02:15,449] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:02:15,449] {logging_mixin.py:109} INFO - [2022-05-17 07:02:15,449] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:02:15,466] {logging_mixin.py:109} INFO - [2022-05-17 07:02:15,463] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:02:15,467] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:02:15,487] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.042 seconds
[2022-05-17 07:02:45,621] {processor.py:163} INFO - Started process (PID=11097) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:02:45,622] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:02:45,623] {logging_mixin.py:109} INFO - [2022-05-17 07:02:45,623] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:02:45,642] {logging_mixin.py:109} INFO - [2022-05-17 07:02:45,638] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:02:45,643] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:02:45,662] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.044 seconds
[2022-05-17 07:03:15,776] {processor.py:163} INFO - Started process (PID=11161) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:03:15,778] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:03:15,778] {logging_mixin.py:109} INFO - [2022-05-17 07:03:15,778] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:03:15,797] {logging_mixin.py:109} INFO - [2022-05-17 07:03:15,794] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:03:15,798] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:03:15,819] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.045 seconds
[2022-05-17 07:03:46,459] {processor.py:163} INFO - Started process (PID=11235) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:03:46,460] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:03:46,461] {logging_mixin.py:109} INFO - [2022-05-17 07:03:46,461] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:03:46,477] {logging_mixin.py:109} INFO - [2022-05-17 07:03:46,475] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:03:46,478] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:03:46,497] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.041 seconds
[2022-05-17 07:04:17,219] {processor.py:163} INFO - Started process (PID=11299) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:04:17,220] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:04:17,221] {logging_mixin.py:109} INFO - [2022-05-17 07:04:17,221] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:04:17,238] {logging_mixin.py:109} INFO - [2022-05-17 07:04:17,235] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:04:17,239] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:04:17,259] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.043 seconds
[2022-05-17 07:04:47,988] {processor.py:163} INFO - Started process (PID=11370) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:04:47,989] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:04:47,990] {logging_mixin.py:109} INFO - [2022-05-17 07:04:47,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:04:48,007] {logging_mixin.py:109} INFO - [2022-05-17 07:04:48,004] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:04:48,008] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:04:48,029] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.043 seconds
[2022-05-17 07:05:18,754] {processor.py:163} INFO - Started process (PID=11443) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:05:18,755] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:05:18,756] {logging_mixin.py:109} INFO - [2022-05-17 07:05:18,756] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:05:18,772] {logging_mixin.py:109} INFO - [2022-05-17 07:05:18,770] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:05:18,773] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:05:18,795] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.044 seconds
[2022-05-17 07:05:49,537] {processor.py:163} INFO - Started process (PID=11506) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:05:49,538] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:05:49,539] {logging_mixin.py:109} INFO - [2022-05-17 07:05:49,539] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:05:49,559] {logging_mixin.py:109} INFO - [2022-05-17 07:05:49,556] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:05:49,560] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:05:49,586] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.052 seconds
[2022-05-17 07:06:20,234] {processor.py:163} INFO - Started process (PID=11579) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:06:20,236] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:06:20,236] {logging_mixin.py:109} INFO - [2022-05-17 07:06:20,236] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:06:20,256] {logging_mixin.py:109} INFO - [2022-05-17 07:06:20,253] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:06:20,257] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:06:20,282] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.050 seconds
[2022-05-17 07:06:50,656] {processor.py:163} INFO - Started process (PID=11642) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:06:50,658] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:06:50,659] {logging_mixin.py:109} INFO - [2022-05-17 07:06:50,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:06:50,688] {logging_mixin.py:109} INFO - [2022-05-17 07:06:50,684] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:06:50,689] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:06:50,764] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.113 seconds
[2022-05-17 07:07:21,127] {processor.py:163} INFO - Started process (PID=11716) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:07:21,129] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:07:21,130] {logging_mixin.py:109} INFO - [2022-05-17 07:07:21,130] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:07:21,166] {logging_mixin.py:109} INFO - [2022-05-17 07:07:21,160] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:07:21,167] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:07:21,211] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.091 seconds
[2022-05-17 07:07:51,312] {processor.py:163} INFO - Started process (PID=11780) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:07:51,314] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:07:51,316] {logging_mixin.py:109} INFO - [2022-05-17 07:07:51,316] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:07:51,338] {logging_mixin.py:109} INFO - [2022-05-17 07:07:51,335] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:07:51,339] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:07:51,368] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.060 seconds
[2022-05-17 07:08:21,595] {processor.py:163} INFO - Started process (PID=11842) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:08:21,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:08:21,598] {logging_mixin.py:109} INFO - [2022-05-17 07:08:21,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:08:21,628] {logging_mixin.py:109} INFO - [2022-05-17 07:08:21,622] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:08:21,629] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:08:21,662] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.072 seconds
[2022-05-17 07:08:51,761] {processor.py:163} INFO - Started process (PID=11905) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:08:51,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:08:51,764] {logging_mixin.py:109} INFO - [2022-05-17 07:08:51,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:08:51,792] {logging_mixin.py:109} INFO - [2022-05-17 07:08:51,789] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:08:51,793] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:08:51,821] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.064 seconds
[2022-05-17 07:09:22,468] {processor.py:163} INFO - Started process (PID=11977) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:09:22,471] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:09:22,473] {logging_mixin.py:109} INFO - [2022-05-17 07:09:22,472] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:09:22,526] {logging_mixin.py:109} INFO - [2022-05-17 07:09:22,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:09:22,528] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:09:22,579] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.118 seconds
[2022-05-17 07:09:53,491] {processor.py:163} INFO - Started process (PID=12041) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:09:53,492] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:09:53,494] {logging_mixin.py:109} INFO - [2022-05-17 07:09:53,494] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:09:53,528] {logging_mixin.py:109} INFO - [2022-05-17 07:09:53,523] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:09:53,531] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:09:53,575] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.089 seconds
[2022-05-17 07:10:24,203] {processor.py:163} INFO - Started process (PID=12103) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:10:24,205] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:10:24,206] {logging_mixin.py:109} INFO - [2022-05-17 07:10:24,206] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:10:24,232] {logging_mixin.py:109} INFO - [2022-05-17 07:10:24,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:10:24,234] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:10:24,263] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.065 seconds
[2022-05-17 07:10:54,582] {processor.py:163} INFO - Started process (PID=12177) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:10:54,583] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:10:54,584] {logging_mixin.py:109} INFO - [2022-05-17 07:10:54,584] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:10:54,616] {logging_mixin.py:109} INFO - [2022-05-17 07:10:54,610] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:10:54,618] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:10:54,653] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.076 seconds
[2022-05-17 07:11:24,723] {processor.py:163} INFO - Started process (PID=12245) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:11:24,725] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:11:24,725] {logging_mixin.py:109} INFO - [2022-05-17 07:11:24,725] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:11:24,754] {logging_mixin.py:109} INFO - [2022-05-17 07:11:24,750] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:11:24,757] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:11:24,791] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.073 seconds
[2022-05-17 07:11:55,359] {processor.py:163} INFO - Started process (PID=12307) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:11:55,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:11:55,365] {logging_mixin.py:109} INFO - [2022-05-17 07:11:55,362] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:11:55,402] {logging_mixin.py:109} INFO - [2022-05-17 07:11:55,393] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:11:55,404] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:11:55,442] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.088 seconds
[2022-05-17 07:12:49,344] {processor.py:163} INFO - Started process (PID=12370) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:12:49,350] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:12:49,352] {logging_mixin.py:109} INFO - [2022-05-17 07:12:49,351] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:12:49,396] {logging_mixin.py:109} INFO - [2022-05-17 07:12:49,389] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:12:49,398] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:12:49,437] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.098 seconds
[2022-05-17 07:13:19,760] {processor.py:163} INFO - Started process (PID=12434) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:13:19,761] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:13:19,762] {logging_mixin.py:109} INFO - [2022-05-17 07:13:19,762] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:13:19,782] {logging_mixin.py:109} INFO - [2022-05-17 07:13:19,779] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:13:19,783] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:13:19,806] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.050 seconds
[2022-05-17 07:13:50,808] {processor.py:163} INFO - Started process (PID=12509) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:13:50,810] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:13:50,811] {logging_mixin.py:109} INFO - [2022-05-17 07:13:50,811] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:13:50,835] {logging_mixin.py:109} INFO - [2022-05-17 07:13:50,832] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:13:50,836] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:13:50,914] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.110 seconds
[2022-05-17 07:14:21,084] {processor.py:163} INFO - Started process (PID=12575) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:14:21,086] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:14:21,086] {logging_mixin.py:109} INFO - [2022-05-17 07:14:21,086] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:14:21,102] {logging_mixin.py:109} INFO - [2022-05-17 07:14:21,099] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:14:21,103] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:14:21,124] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.043 seconds
[2022-05-17 07:14:52,071] {processor.py:163} INFO - Started process (PID=12648) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:14:52,072] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:14:52,073] {logging_mixin.py:109} INFO - [2022-05-17 07:14:52,073] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:14:52,089] {logging_mixin.py:109} INFO - [2022-05-17 07:14:52,087] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:14:52,090] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:14:52,114] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.046 seconds
[2022-05-17 07:15:22,874] {processor.py:163} INFO - Started process (PID=12712) to work on /opt/airflow/dags/ej8.py
[2022-05-17 07:15:22,875] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-17 07:15:22,876] {logging_mixin.py:109} INFO - [2022-05-17 07:15:22,876] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-17 07:15:22,897] {logging_mixin.py:109} INFO - [2022-05-17 07:15:22,893] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-17 07:15:22,899] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-17 07:15:22,923] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.052 seconds
