[2022-05-04 15:26:57,651] {processor.py:163} INFO - Started process (PID=15162) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:26:57,667] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:26:57,683] {logging_mixin.py:109} INFO - [2022-05-04 15:26:57,683] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:26:58,328] {logging_mixin.py:109} INFO - [2022-05-04 15:26:58,234] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:26:58,377] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:26:58,534] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.900 seconds
[2022-05-04 15:27:33,058] {processor.py:163} INFO - Started process (PID=15223) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:27:33,065] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:27:33,068] {logging_mixin.py:109} INFO - [2022-05-04 15:27:33,068] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:27:33,225] {logging_mixin.py:109} INFO - [2022-05-04 15:27:33,185] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:27:33,243] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:27:33,316] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.274 seconds
[2022-05-04 15:28:03,499] {processor.py:163} INFO - Started process (PID=15282) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:28:03,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:28:03,510] {logging_mixin.py:109} INFO - [2022-05-04 15:28:03,506] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:28:03,588] {logging_mixin.py:109} INFO - [2022-05-04 15:28:03,566] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:28:03,591] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:28:03,656] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.163 seconds
[2022-05-04 15:28:33,925] {processor.py:163} INFO - Started process (PID=15334) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:28:33,928] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:28:33,930] {logging_mixin.py:109} INFO - [2022-05-04 15:28:33,930] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:28:33,984] {logging_mixin.py:109} INFO - [2022-05-04 15:28:33,967] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:28:33,986] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:28:34,047] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.131 seconds
[2022-05-04 15:29:04,422] {processor.py:163} INFO - Started process (PID=15390) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:29:04,424] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:29:04,425] {logging_mixin.py:109} INFO - [2022-05-04 15:29:04,425] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:29:04,458] {logging_mixin.py:109} INFO - [2022-05-04 15:29:04,453] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:29:04,459] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:29:04,500] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 15:29:34,793] {processor.py:163} INFO - Started process (PID=15458) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:29:34,795] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:29:34,797] {logging_mixin.py:109} INFO - [2022-05-04 15:29:34,797] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:29:34,847] {logging_mixin.py:109} INFO - [2022-05-04 15:29:34,837] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:29:34,849] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:29:34,899] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.112 seconds
[2022-05-04 15:30:05,376] {processor.py:163} INFO - Started process (PID=15518) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:30:05,379] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:30:05,380] {logging_mixin.py:109} INFO - [2022-05-04 15:30:05,380] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:30:05,411] {logging_mixin.py:109} INFO - [2022-05-04 15:30:05,407] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:30:05,413] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:30:05,445] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-04 15:30:35,811] {processor.py:163} INFO - Started process (PID=15578) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:30:35,814] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:30:35,815] {logging_mixin.py:109} INFO - [2022-05-04 15:30:35,815] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:30:35,878] {logging_mixin.py:109} INFO - [2022-05-04 15:30:35,873] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:30:35,880] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:30:35,915] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.112 seconds
[2022-05-04 15:31:06,445] {processor.py:163} INFO - Started process (PID=15638) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:31:06,449] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:31:06,451] {logging_mixin.py:109} INFO - [2022-05-04 15:31:06,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:31:06,486] {logging_mixin.py:109} INFO - [2022-05-04 15:31:06,478] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:31:06,488] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:31:06,528] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.088 seconds
[2022-05-04 15:31:37,104] {processor.py:163} INFO - Started process (PID=15708) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:31:37,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:31:37,108] {logging_mixin.py:109} INFO - [2022-05-04 15:31:37,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:31:37,165] {logging_mixin.py:109} INFO - [2022-05-04 15:31:37,160] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:31:37,168] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:31:37,211] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.114 seconds
[2022-05-04 15:32:07,809] {processor.py:163} INFO - Started process (PID=15769) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:32:07,812] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:32:07,814] {logging_mixin.py:109} INFO - [2022-05-04 15:32:07,814] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:32:07,875] {logging_mixin.py:109} INFO - [2022-05-04 15:32:07,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:32:07,878] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:32:07,924] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.121 seconds
[2022-05-04 15:32:38,760] {processor.py:163} INFO - Started process (PID=15829) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:32:38,762] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:32:38,764] {logging_mixin.py:109} INFO - [2022-05-04 15:32:38,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:32:38,791] {logging_mixin.py:109} INFO - [2022-05-04 15:32:38,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:32:38,792] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:32:38,823] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-04 15:33:09,205] {processor.py:163} INFO - Started process (PID=15900) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:33:09,209] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:33:09,210] {logging_mixin.py:109} INFO - [2022-05-04 15:33:09,210] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:33:09,252] {logging_mixin.py:109} INFO - [2022-05-04 15:33:09,245] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:33:09,256] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:33:09,314] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.119 seconds
[2022-05-04 15:33:40,073] {processor.py:163} INFO - Started process (PID=15961) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:33:40,074] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:33:40,075] {logging_mixin.py:109} INFO - [2022-05-04 15:33:40,075] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:33:40,109] {logging_mixin.py:109} INFO - [2022-05-04 15:33:40,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:33:40,111] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:33:40,142] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 15:34:10,586] {processor.py:163} INFO - Started process (PID=16021) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:34:10,588] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:34:10,589] {logging_mixin.py:109} INFO - [2022-05-04 15:34:10,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:34:10,621] {logging_mixin.py:109} INFO - [2022-05-04 15:34:10,616] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:34:10,623] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:34:10,656] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.074 seconds
[2022-05-04 15:34:40,991] {processor.py:163} INFO - Started process (PID=16091) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:34:40,993] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:34:40,994] {logging_mixin.py:109} INFO - [2022-05-04 15:34:40,994] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:34:41,027] {logging_mixin.py:109} INFO - [2022-05-04 15:34:41,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:34:41,028] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:34:41,064] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.078 seconds
[2022-05-04 15:35:11,825] {processor.py:163} INFO - Started process (PID=16151) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:35:11,827] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:35:11,828] {logging_mixin.py:109} INFO - [2022-05-04 15:35:11,828] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:35:11,848] {logging_mixin.py:109} INFO - [2022-05-04 15:35:11,845] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:35:11,849] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:35:11,869] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.048 seconds
[2022-05-04 15:35:42,426] {processor.py:163} INFO - Started process (PID=16221) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:35:42,428] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:35:42,429] {logging_mixin.py:109} INFO - [2022-05-04 15:35:42,429] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:35:42,452] {logging_mixin.py:109} INFO - [2022-05-04 15:35:42,449] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:35:42,454] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:35:42,478] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-04 15:36:12,591] {processor.py:163} INFO - Started process (PID=16280) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:36:12,593] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:36:12,594] {logging_mixin.py:109} INFO - [2022-05-04 15:36:12,594] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:36:12,619] {logging_mixin.py:109} INFO - [2022-05-04 15:36:12,614] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:36:12,621] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:36:12,646] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.059 seconds
[2022-05-04 15:36:43,204] {processor.py:163} INFO - Started process (PID=16351) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:36:43,207] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:36:43,208] {logging_mixin.py:109} INFO - [2022-05-04 15:36:43,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:36:43,235] {logging_mixin.py:109} INFO - [2022-05-04 15:36:43,230] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:36:43,238] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:36:43,274] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.074 seconds
[2022-05-04 15:37:13,466] {processor.py:163} INFO - Started process (PID=16411) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:37:13,468] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:37:13,470] {logging_mixin.py:109} INFO - [2022-05-04 15:37:13,470] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:37:13,491] {logging_mixin.py:109} INFO - [2022-05-04 15:37:13,488] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:37:13,492] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:37:13,523] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.060 seconds
[2022-05-04 15:37:43,761] {processor.py:163} INFO - Started process (PID=16484) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:37:43,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:37:43,763] {logging_mixin.py:109} INFO - [2022-05-04 15:37:43,763] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:37:43,786] {logging_mixin.py:109} INFO - [2022-05-04 15:37:43,782] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:37:43,788] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:37:43,817] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-04 15:38:14,044] {processor.py:163} INFO - Started process (PID=16534) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:38:14,046] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:38:14,047] {logging_mixin.py:109} INFO - [2022-05-04 15:38:14,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:38:14,063] {logging_mixin.py:109} INFO - [2022-05-04 15:38:14,060] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:38:14,065] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:38:14,091] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.050 seconds
[2022-05-04 15:38:44,210] {processor.py:163} INFO - Started process (PID=16600) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:38:44,211] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:38:44,212] {logging_mixin.py:109} INFO - [2022-05-04 15:38:44,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:38:44,235] {logging_mixin.py:109} INFO - [2022-05-04 15:38:44,231] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:38:44,236] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:38:44,261] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.054 seconds
[2022-05-04 15:39:14,617] {processor.py:163} INFO - Started process (PID=16661) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:39:14,618] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:39:14,619] {logging_mixin.py:109} INFO - [2022-05-04 15:39:14,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:39:14,641] {logging_mixin.py:109} INFO - [2022-05-04 15:39:14,636] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:39:14,642] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:39:14,667] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.054 seconds
[2022-05-04 15:39:45,446] {processor.py:163} INFO - Started process (PID=16729) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:39:45,447] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:39:45,448] {logging_mixin.py:109} INFO - [2022-05-04 15:39:45,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:39:45,470] {logging_mixin.py:109} INFO - [2022-05-04 15:39:45,465] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:39:45,471] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:39:45,498] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-04 15:40:15,707] {processor.py:163} INFO - Started process (PID=16789) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:40:15,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:40:15,710] {logging_mixin.py:109} INFO - [2022-05-04 15:40:15,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:40:15,734] {logging_mixin.py:109} INFO - [2022-05-04 15:40:15,730] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:40:15,736] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:40:15,767] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.062 seconds
[2022-05-04 15:40:46,071] {processor.py:163} INFO - Started process (PID=16859) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:40:46,073] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:40:46,075] {logging_mixin.py:109} INFO - [2022-05-04 15:40:46,074] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:40:46,104] {logging_mixin.py:109} INFO - [2022-05-04 15:40:46,099] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:40:46,105] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:40:46,132] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.065 seconds
[2022-05-04 15:41:16,413] {processor.py:163} INFO - Started process (PID=16918) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:41:16,415] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:41:16,416] {logging_mixin.py:109} INFO - [2022-05-04 15:41:16,416] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:41:16,443] {logging_mixin.py:109} INFO - [2022-05-04 15:41:16,439] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:41:16,444] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:41:16,473] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.063 seconds
[2022-05-04 15:41:46,552] {processor.py:163} INFO - Started process (PID=16987) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:41:46,554] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:41:46,555] {logging_mixin.py:109} INFO - [2022-05-04 15:41:46,555] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:41:46,575] {logging_mixin.py:109} INFO - [2022-05-04 15:41:46,572] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:41:46,576] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:41:46,597] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.049 seconds
[2022-05-04 15:42:17,124] {processor.py:163} INFO - Started process (PID=17045) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:42:17,126] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:42:17,126] {logging_mixin.py:109} INFO - [2022-05-04 15:42:17,126] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:42:17,148] {logging_mixin.py:109} INFO - [2022-05-04 15:42:17,144] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:42:17,150] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:42:17,176] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.055 seconds
[2022-05-04 15:43:03,438] {processor.py:163} INFO - Started process (PID=17098) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:43:03,440] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:43:03,457] {logging_mixin.py:109} INFO - [2022-05-04 15:43:03,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:43:03,555] {logging_mixin.py:109} INFO - [2022-05-04 15:43:03,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:43:03,556] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:43:03,589] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.155 seconds
[2022-05-04 15:48:01,157] {processor.py:163} INFO - Started process (PID=17143) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:48:01,159] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:48:01,160] {logging_mixin.py:109} INFO - [2022-05-04 15:48:01,160] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:48:01,187] {logging_mixin.py:109} INFO - [2022-05-04 15:48:01,182] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:48:01,189] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:48:01,222] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.069 seconds
[2022-05-04 15:48:31,516] {processor.py:163} INFO - Started process (PID=17202) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:48:31,518] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:48:31,519] {logging_mixin.py:109} INFO - [2022-05-04 15:48:31,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:48:31,557] {logging_mixin.py:109} INFO - [2022-05-04 15:48:31,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:48:31,560] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:48:31,585] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 15:49:01,670] {processor.py:163} INFO - Started process (PID=17271) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:49:01,671] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:49:01,672] {logging_mixin.py:109} INFO - [2022-05-04 15:49:01,672] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:49:01,716] {logging_mixin.py:109} INFO - [2022-05-04 15:49:01,711] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:49:01,717] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:49:01,746] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.081 seconds
[2022-05-04 15:49:32,430] {processor.py:163} INFO - Started process (PID=17332) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:49:32,431] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:49:32,432] {logging_mixin.py:109} INFO - [2022-05-04 15:49:32,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:49:32,477] {logging_mixin.py:109} INFO - [2022-05-04 15:49:32,468] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:49:32,479] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:49:32,507] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-04 15:50:03,177] {processor.py:163} INFO - Started process (PID=17400) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:50:03,180] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:50:03,181] {logging_mixin.py:109} INFO - [2022-05-04 15:50:03,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:50:03,225] {logging_mixin.py:109} INFO - [2022-05-04 15:50:03,217] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:50:03,227] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:50:03,257] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 15:50:33,909] {processor.py:163} INFO - Started process (PID=17461) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:50:33,911] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:50:33,912] {logging_mixin.py:109} INFO - [2022-05-04 15:50:33,912] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:50:33,941] {logging_mixin.py:109} INFO - [2022-05-04 15:50:33,937] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:50:33,942] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:50:33,966] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.061 seconds
[2022-05-04 15:51:04,613] {processor.py:163} INFO - Started process (PID=17531) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:51:04,615] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:51:04,616] {logging_mixin.py:109} INFO - [2022-05-04 15:51:04,616] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:51:04,657] {logging_mixin.py:109} INFO - [2022-05-04 15:51:04,649] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:51:04,660] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:51:04,688] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-04 15:51:34,976] {processor.py:163} INFO - Started process (PID=17591) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:51:34,977] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:51:34,978] {logging_mixin.py:109} INFO - [2022-05-04 15:51:34,978] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:51:35,019] {logging_mixin.py:109} INFO - [2022-05-04 15:51:35,012] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:51:35,022] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:51:35,051] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.079 seconds
[2022-05-04 15:52:05,555] {processor.py:163} INFO - Started process (PID=17661) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:52:05,556] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:52:05,557] {logging_mixin.py:109} INFO - [2022-05-04 15:52:05,557] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:52:05,597] {logging_mixin.py:109} INFO - [2022-05-04 15:52:05,590] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:52:05,599] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:52:05,626] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 15:52:36,533] {processor.py:163} INFO - Started process (PID=17731) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:52:36,535] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:52:36,536] {logging_mixin.py:109} INFO - [2022-05-04 15:52:36,536] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:52:36,568] {logging_mixin.py:109} INFO - [2022-05-04 15:52:36,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:52:36,570] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:52:36,597] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.069 seconds
[2022-05-04 15:53:07,006] {processor.py:163} INFO - Started process (PID=17791) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:53:07,008] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:53:07,010] {logging_mixin.py:109} INFO - [2022-05-04 15:53:07,009] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:53:07,050] {logging_mixin.py:109} INFO - [2022-05-04 15:53:07,042] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:53:07,052] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:53:07,078] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 15:53:37,746] {processor.py:163} INFO - Started process (PID=17860) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:53:37,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:53:37,748] {logging_mixin.py:109} INFO - [2022-05-04 15:53:37,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:53:37,788] {logging_mixin.py:109} INFO - [2022-05-04 15:53:37,780] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:53:37,791] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:53:37,823] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-04 15:54:08,215] {processor.py:163} INFO - Started process (PID=17920) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:54:08,217] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:54:08,218] {logging_mixin.py:109} INFO - [2022-05-04 15:54:08,218] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:54:08,258] {logging_mixin.py:109} INFO - [2022-05-04 15:54:08,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:54:08,261] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:54:08,286] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 15:54:38,534] {processor.py:163} INFO - Started process (PID=17989) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:54:38,536] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:54:38,537] {logging_mixin.py:109} INFO - [2022-05-04 15:54:38,537] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:54:38,581] {logging_mixin.py:109} INFO - [2022-05-04 15:54:38,573] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:54:38,584] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:54:38,615] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.084 seconds
[2022-05-04 15:55:09,130] {processor.py:163} INFO - Started process (PID=18056) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:55:09,133] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:55:09,134] {logging_mixin.py:109} INFO - [2022-05-04 15:55:09,134] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:55:09,167] {logging_mixin.py:109} INFO - [2022-05-04 15:55:09,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:55:09,168] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:55:09,194] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.068 seconds
[2022-05-04 15:55:39,824] {processor.py:163} INFO - Started process (PID=18120) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:55:39,826] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:55:39,827] {logging_mixin.py:109} INFO - [2022-05-04 15:55:39,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:55:39,858] {logging_mixin.py:109} INFO - [2022-05-04 15:55:39,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:55:39,861] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:55:39,889] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.069 seconds
[2022-05-04 15:56:10,598] {processor.py:163} INFO - Started process (PID=18189) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:56:10,599] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:56:10,600] {logging_mixin.py:109} INFO - [2022-05-04 15:56:10,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:56:10,641] {logging_mixin.py:109} INFO - [2022-05-04 15:56:10,636] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:56:10,642] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:56:10,670] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 15:56:41,190] {processor.py:163} INFO - Started process (PID=18249) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:56:41,192] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:56:41,193] {logging_mixin.py:109} INFO - [2022-05-04 15:56:41,193] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:56:41,233] {logging_mixin.py:109} INFO - [2022-05-04 15:56:41,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:56:41,236] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:56:41,264] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-04 15:57:11,390] {processor.py:163} INFO - Started process (PID=18318) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:57:11,392] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:57:11,393] {logging_mixin.py:109} INFO - [2022-05-04 15:57:11,393] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:57:11,429] {logging_mixin.py:109} INFO - [2022-05-04 15:57:11,424] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:57:11,431] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:57:11,457] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.070 seconds
[2022-05-04 15:57:41,589] {processor.py:163} INFO - Started process (PID=18379) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:57:41,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:57:41,592] {logging_mixin.py:109} INFO - [2022-05-04 15:57:41,592] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:57:41,632] {logging_mixin.py:109} INFO - [2022-05-04 15:57:41,625] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:57:41,633] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:57:41,658] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 15:58:12,590] {processor.py:163} INFO - Started process (PID=18448) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:58:12,592] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:58:12,593] {logging_mixin.py:109} INFO - [2022-05-04 15:58:12,593] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:58:12,626] {logging_mixin.py:109} INFO - [2022-05-04 15:58:12,620] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:58:12,627] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:58:12,652] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-04 15:58:42,995] {processor.py:163} INFO - Started process (PID=18517) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:58:42,997] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:58:42,999] {logging_mixin.py:109} INFO - [2022-05-04 15:58:42,998] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:58:43,036] {logging_mixin.py:109} INFO - [2022-05-04 15:58:43,030] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:58:43,038] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:58:43,066] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 15:59:13,805] {processor.py:163} INFO - Started process (PID=18576) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:59:13,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:59:13,807] {logging_mixin.py:109} INFO - [2022-05-04 15:59:13,807] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:59:13,854] {logging_mixin.py:109} INFO - [2022-05-04 15:59:13,846] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:59:13,856] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:59:13,888] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-04 15:59:44,475] {processor.py:163} INFO - Started process (PID=18645) to work on /opt/airflow/dags/ej4.py
[2022-05-04 15:59:44,477] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 15:59:44,478] {logging_mixin.py:109} INFO - [2022-05-04 15:59:44,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 15:59:44,519] {logging_mixin.py:109} INFO - [2022-05-04 15:59:44,512] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 15:59:44,522] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 15:59:44,548] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.076 seconds
[2022-05-04 16:00:14,990] {processor.py:163} INFO - Started process (PID=18704) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:00:14,992] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:00:14,993] {logging_mixin.py:109} INFO - [2022-05-04 16:00:14,993] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:00:15,033] {logging_mixin.py:109} INFO - [2022-05-04 16:00:15,027] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:00:15,035] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:00:15,071] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-04 16:00:45,698] {processor.py:163} INFO - Started process (PID=18775) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:00:45,701] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:00:45,702] {logging_mixin.py:109} INFO - [2022-05-04 16:00:45,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:00:45,741] {logging_mixin.py:109} INFO - [2022-05-04 16:00:45,735] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:00:45,743] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:00:45,773] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-04 16:01:16,252] {processor.py:163} INFO - Started process (PID=18835) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:01:16,254] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:01:16,256] {logging_mixin.py:109} INFO - [2022-05-04 16:01:16,255] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:01:16,293] {logging_mixin.py:109} INFO - [2022-05-04 16:01:16,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:01:16,294] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:01:16,322] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.074 seconds
[2022-05-04 16:01:46,822] {processor.py:163} INFO - Started process (PID=18904) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:01:46,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:01:46,826] {logging_mixin.py:109} INFO - [2022-05-04 16:01:46,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:01:46,870] {logging_mixin.py:109} INFO - [2022-05-04 16:01:46,863] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:01:46,872] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:01:46,901] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 16:02:17,674] {processor.py:163} INFO - Started process (PID=18963) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:02:17,676] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:02:17,678] {logging_mixin.py:109} INFO - [2022-05-04 16:02:17,678] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:02:17,722] {logging_mixin.py:109} INFO - [2022-05-04 16:02:17,714] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:02:17,725] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:02:17,771] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.102 seconds
[2022-05-04 16:02:48,064] {processor.py:163} INFO - Started process (PID=19033) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:02:48,066] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:02:48,067] {logging_mixin.py:109} INFO - [2022-05-04 16:02:48,067] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:02:48,104] {logging_mixin.py:109} INFO - [2022-05-04 16:02:48,099] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:02:48,106] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:02:48,134] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 16:03:18,251] {processor.py:163} INFO - Started process (PID=19094) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:03:18,253] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:03:18,255] {logging_mixin.py:109} INFO - [2022-05-04 16:03:18,255] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:03:18,293] {logging_mixin.py:109} INFO - [2022-05-04 16:03:18,285] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:03:18,296] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:03:18,331] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.085 seconds
[2022-05-04 16:03:48,739] {processor.py:163} INFO - Started process (PID=19163) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:03:48,741] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:03:48,742] {logging_mixin.py:109} INFO - [2022-05-04 16:03:48,742] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:03:48,772] {logging_mixin.py:109} INFO - [2022-05-04 16:03:48,767] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:03:48,774] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:03:48,801] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.066 seconds
[2022-05-04 16:04:19,120] {processor.py:163} INFO - Started process (PID=19223) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:04:19,122] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:04:19,124] {logging_mixin.py:109} INFO - [2022-05-04 16:04:19,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:04:19,164] {logging_mixin.py:109} INFO - [2022-05-04 16:04:19,157] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:04:19,166] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:04:19,199] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 16:04:49,791] {processor.py:163} INFO - Started process (PID=19291) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:04:49,793] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:04:49,795] {logging_mixin.py:109} INFO - [2022-05-04 16:04:49,795] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:04:49,827] {logging_mixin.py:109} INFO - [2022-05-04 16:04:49,822] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:04:49,829] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:04:49,857] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.071 seconds
[2022-05-04 16:05:20,043] {processor.py:163} INFO - Started process (PID=19354) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:05:20,045] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:05:20,047] {logging_mixin.py:109} INFO - [2022-05-04 16:05:20,046] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:05:20,076] {logging_mixin.py:109} INFO - [2022-05-04 16:05:20,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:05:20,078] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:05:20,107] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.068 seconds
[2022-05-04 16:05:50,596] {processor.py:163} INFO - Started process (PID=19415) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:05:50,598] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:05:50,600] {logging_mixin.py:109} INFO - [2022-05-04 16:05:50,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:05:50,647] {logging_mixin.py:109} INFO - [2022-05-04 16:05:50,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:05:50,648] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:05:50,677] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.090 seconds
[2022-05-04 16:06:21,133] {processor.py:163} INFO - Started process (PID=19486) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:06:21,135] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:06:21,136] {logging_mixin.py:109} INFO - [2022-05-04 16:06:21,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:06:21,170] {logging_mixin.py:109} INFO - [2022-05-04 16:06:21,162] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:06:21,172] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:06:21,200] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.071 seconds
[2022-05-04 16:06:52,061] {processor.py:163} INFO - Started process (PID=19545) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:06:52,063] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:06:52,064] {logging_mixin.py:109} INFO - [2022-05-04 16:06:52,064] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:06:52,094] {logging_mixin.py:109} INFO - [2022-05-04 16:06:52,088] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:06:52,095] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:06:52,128] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.072 seconds
[2022-05-04 16:07:22,733] {processor.py:163} INFO - Started process (PID=19613) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:07:22,735] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:07:22,737] {logging_mixin.py:109} INFO - [2022-05-04 16:07:22,737] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:07:22,785] {logging_mixin.py:109} INFO - [2022-05-04 16:07:22,778] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:07:22,787] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:07:22,815] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.090 seconds
[2022-05-04 16:07:53,431] {processor.py:163} INFO - Started process (PID=19673) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:07:53,433] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:07:53,435] {logging_mixin.py:109} INFO - [2022-05-04 16:07:53,435] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:07:53,479] {logging_mixin.py:109} INFO - [2022-05-04 16:07:53,472] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:07:53,481] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:07:53,512] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.087 seconds
[2022-05-04 16:08:23,641] {processor.py:163} INFO - Started process (PID=19743) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:08:23,643] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:08:23,645] {logging_mixin.py:109} INFO - [2022-05-04 16:08:23,645] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:08:23,681] {logging_mixin.py:109} INFO - [2022-05-04 16:08:23,674] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:08:23,683] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:08:23,712] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-04 16:08:53,861] {processor.py:163} INFO - Started process (PID=19803) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:08:53,863] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:08:53,865] {logging_mixin.py:109} INFO - [2022-05-04 16:08:53,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:08:53,910] {logging_mixin.py:109} INFO - [2022-05-04 16:08:53,901] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:08:53,912] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:08:53,944] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.087 seconds
[2022-05-04 16:09:24,527] {processor.py:163} INFO - Started process (PID=19874) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:09:24,529] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:09:24,530] {logging_mixin.py:109} INFO - [2022-05-04 16:09:24,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:09:24,564] {logging_mixin.py:109} INFO - [2022-05-04 16:09:24,558] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:09:24,566] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:09:24,608] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.085 seconds
[2022-05-04 16:09:55,145] {processor.py:163} INFO - Started process (PID=19935) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:09:55,147] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:09:55,148] {logging_mixin.py:109} INFO - [2022-05-04 16:09:55,148] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:09:55,189] {logging_mixin.py:109} INFO - [2022-05-04 16:09:55,183] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:09:55,191] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:09:55,217] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-04 16:10:25,492] {processor.py:163} INFO - Started process (PID=20004) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:10:25,494] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:10:25,495] {logging_mixin.py:109} INFO - [2022-05-04 16:10:25,495] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:10:25,531] {logging_mixin.py:109} INFO - [2022-05-04 16:10:25,525] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:10:25,532] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:10:25,562] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 16:10:55,712] {processor.py:163} INFO - Started process (PID=20064) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:10:55,714] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:10:55,716] {logging_mixin.py:109} INFO - [2022-05-04 16:10:55,715] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:10:55,768] {logging_mixin.py:109} INFO - [2022-05-04 16:10:55,759] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:10:55,770] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:10:55,799] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.094 seconds
[2022-05-04 16:11:26,370] {processor.py:163} INFO - Started process (PID=20134) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:11:26,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:11:26,373] {logging_mixin.py:109} INFO - [2022-05-04 16:11:26,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:11:26,410] {logging_mixin.py:109} INFO - [2022-05-04 16:11:26,403] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:11:26,412] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:11:26,445] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.080 seconds
[2022-05-04 16:11:56,873] {processor.py:163} INFO - Started process (PID=20193) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:11:56,875] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:11:56,876] {logging_mixin.py:109} INFO - [2022-05-04 16:11:56,876] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:11:56,920] {logging_mixin.py:109} INFO - [2022-05-04 16:11:56,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:11:56,923] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:11:56,956] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.087 seconds
[2022-05-04 16:12:27,058] {processor.py:163} INFO - Started process (PID=20259) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:12:27,060] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:12:27,062] {logging_mixin.py:109} INFO - [2022-05-04 16:12:27,062] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:12:27,104] {logging_mixin.py:109} INFO - [2022-05-04 16:12:27,096] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:12:27,106] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:12:27,135] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 16:12:57,292] {processor.py:163} INFO - Started process (PID=20322) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:12:57,294] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:12:57,296] {logging_mixin.py:109} INFO - [2022-05-04 16:12:57,295] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:12:57,337] {logging_mixin.py:109} INFO - [2022-05-04 16:12:57,330] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:12:57,339] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:12:57,368] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.083 seconds
[2022-05-04 16:13:27,757] {processor.py:163} INFO - Started process (PID=20383) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:13:27,759] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:13:27,760] {logging_mixin.py:109} INFO - [2022-05-04 16:13:27,760] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:13:27,802] {logging_mixin.py:109} INFO - [2022-05-04 16:13:27,795] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:13:27,805] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:13:27,837] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.085 seconds
[2022-05-04 16:13:58,080] {processor.py:163} INFO - Started process (PID=20455) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:13:58,083] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:13:58,084] {logging_mixin.py:109} INFO - [2022-05-04 16:13:58,084] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:13:58,120] {logging_mixin.py:109} INFO - [2022-05-04 16:13:58,113] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:13:58,122] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:13:58,154] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.079 seconds
[2022-05-04 16:14:28,235] {processor.py:163} INFO - Started process (PID=20515) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:14:28,237] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:14:28,238] {logging_mixin.py:109} INFO - [2022-05-04 16:14:28,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:14:28,278] {logging_mixin.py:109} INFO - [2022-05-04 16:14:28,272] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:14:28,280] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:14:28,310] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.078 seconds
[2022-05-04 16:14:59,048] {processor.py:163} INFO - Started process (PID=20585) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:14:59,051] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:14:59,052] {logging_mixin.py:109} INFO - [2022-05-04 16:14:59,052] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:14:59,094] {logging_mixin.py:109} INFO - [2022-05-04 16:14:59,086] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:14:59,097] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:14:59,127] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.082 seconds
[2022-05-04 16:15:29,352] {processor.py:163} INFO - Started process (PID=20645) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:15:29,355] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:15:29,356] {logging_mixin.py:109} INFO - [2022-05-04 16:15:29,356] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:15:29,399] {logging_mixin.py:109} INFO - [2022-05-04 16:15:29,392] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:15:29,402] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:15:29,431] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.084 seconds
[2022-05-04 16:15:59,830] {processor.py:163} INFO - Started process (PID=20715) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:15:59,832] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:15:59,833] {logging_mixin.py:109} INFO - [2022-05-04 16:15:59,833] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:15:59,878] {logging_mixin.py:109} INFO - [2022-05-04 16:15:59,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:15:59,881] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:15:59,910] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-04 16:16:30,325] {processor.py:163} INFO - Started process (PID=20776) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:16:30,327] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:16:30,328] {logging_mixin.py:109} INFO - [2022-05-04 16:16:30,328] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:16:30,374] {logging_mixin.py:109} INFO - [2022-05-04 16:16:30,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:16:30,376] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:16:30,412] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.090 seconds
[2022-05-04 16:17:00,630] {processor.py:163} INFO - Started process (PID=20846) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:17:00,632] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:17:00,633] {logging_mixin.py:109} INFO - [2022-05-04 16:17:00,633] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:17:00,672] {logging_mixin.py:109} INFO - [2022-05-04 16:17:00,664] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:17:00,674] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:17:00,704] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.079 seconds
[2022-05-04 16:17:30,903] {processor.py:163} INFO - Started process (PID=20906) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:17:30,906] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:17:30,907] {logging_mixin.py:109} INFO - [2022-05-04 16:17:30,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:17:30,949] {logging_mixin.py:109} INFO - [2022-05-04 16:17:30,942] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:17:30,952] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:17:30,983] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.085 seconds
[2022-05-04 16:18:01,489] {processor.py:163} INFO - Started process (PID=20976) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:18:01,492] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:18:01,493] {logging_mixin.py:109} INFO - [2022-05-04 16:18:01,493] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:18:01,535] {logging_mixin.py:109} INFO - [2022-05-04 16:18:01,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:18:01,538] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:18:01,569] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.084 seconds
[2022-05-04 16:18:31,839] {processor.py:163} INFO - Started process (PID=21036) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:18:31,841] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:18:31,842] {logging_mixin.py:109} INFO - [2022-05-04 16:18:31,842] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:18:31,885] {logging_mixin.py:109} INFO - [2022-05-04 16:18:31,877] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:18:31,887] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:18:31,915] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.081 seconds
[2022-05-04 16:19:02,650] {processor.py:163} INFO - Started process (PID=21107) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:19:02,652] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:19:02,653] {logging_mixin.py:109} INFO - [2022-05-04 16:19:02,653] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:19:02,695] {logging_mixin.py:109} INFO - [2022-05-04 16:19:02,688] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:19:02,698] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:19:02,733] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-04 16:19:33,141] {processor.py:163} INFO - Started process (PID=21166) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:19:33,143] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:19:33,145] {logging_mixin.py:109} INFO - [2022-05-04 16:19:33,145] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:19:33,178] {logging_mixin.py:109} INFO - [2022-05-04 16:19:33,173] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:19:33,180] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:19:33,213] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.077 seconds
[2022-05-04 16:20:03,851] {processor.py:163} INFO - Started process (PID=21226) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:20:03,853] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:20:03,854] {logging_mixin.py:109} INFO - [2022-05-04 16:20:03,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:20:03,884] {logging_mixin.py:109} INFO - [2022-05-04 16:20:03,879] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:20:03,886] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:20:03,912] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.065 seconds
[2022-05-04 16:20:34,431] {processor.py:163} INFO - Started process (PID=21297) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:20:34,434] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:20:34,436] {logging_mixin.py:109} INFO - [2022-05-04 16:20:34,436] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:20:34,482] {logging_mixin.py:109} INFO - [2022-05-04 16:20:34,476] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:20:34,484] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:20:34,514] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.092 seconds
[2022-05-04 16:21:05,032] {processor.py:163} INFO - Started process (PID=21357) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:21:05,036] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:21:05,038] {logging_mixin.py:109} INFO - [2022-05-04 16:21:05,038] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:21:05,098] {logging_mixin.py:109} INFO - [2022-05-04 16:21:05,090] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:21:05,101] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:21:05,135] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.111 seconds
[2022-05-04 16:21:35,755] {processor.py:163} INFO - Started process (PID=21427) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:21:35,758] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:21:35,759] {logging_mixin.py:109} INFO - [2022-05-04 16:21:35,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:21:35,806] {logging_mixin.py:109} INFO - [2022-05-04 16:21:35,798] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:21:35,808] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:21:35,837] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.091 seconds
[2022-05-04 16:22:06,565] {processor.py:163} INFO - Started process (PID=21486) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:22:06,566] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:22:06,567] {logging_mixin.py:109} INFO - [2022-05-04 16:22:06,567] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:22:06,606] {logging_mixin.py:109} INFO - [2022-05-04 16:22:06,600] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:22:06,608] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:22:06,635] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.075 seconds
[2022-05-04 16:22:37,246] {processor.py:163} INFO - Started process (PID=21556) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:22:37,249] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:22:37,251] {logging_mixin.py:109} INFO - [2022-05-04 16:22:37,251] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:22:37,292] {logging_mixin.py:109} INFO - [2022-05-04 16:22:37,283] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:22:37,295] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:22:37,331] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.091 seconds
[2022-05-04 16:23:07,772] {processor.py:163} INFO - Started process (PID=21616) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:23:07,774] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:23:07,775] {logging_mixin.py:109} INFO - [2022-05-04 16:23:07,775] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:23:07,810] {logging_mixin.py:109} INFO - [2022-05-04 16:23:07,804] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:23:07,812] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:23:07,840] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.073 seconds
[2022-05-04 16:23:38,577] {processor.py:163} INFO - Started process (PID=21687) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:23:38,579] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:23:38,580] {logging_mixin.py:109} INFO - [2022-05-04 16:23:38,580] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:23:38,625] {logging_mixin.py:109} INFO - [2022-05-04 16:23:38,618] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:23:38,628] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:23:38,655] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.086 seconds
[2022-05-04 16:24:09,208] {processor.py:163} INFO - Started process (PID=21748) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:24:09,211] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:24:09,212] {logging_mixin.py:109} INFO - [2022-05-04 16:24:09,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:24:09,256] {logging_mixin.py:109} INFO - [2022-05-04 16:24:09,249] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:24:09,259] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:24:09,294] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.094 seconds
[2022-05-04 16:24:39,887] {processor.py:163} INFO - Started process (PID=21817) to work on /opt/airflow/dags/ej4.py
[2022-05-04 16:24:39,889] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 16:24:39,890] {logging_mixin.py:109} INFO - [2022-05-04 16:24:39,890] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 16:24:39,931] {logging_mixin.py:109} INFO - [2022-05-04 16:24:39,923] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 16:24:39,933] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 16:24:39,965] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.084 seconds
[2022-05-04 17:29:31,802] {processor.py:163} INFO - Started process (PID=21888) to work on /opt/airflow/dags/ej4.py
[2022-05-04 17:29:31,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 17:29:31,812] {logging_mixin.py:109} INFO - [2022-05-04 17:29:31,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 17:29:31,933] {logging_mixin.py:109} INFO - [2022-05-04 17:29:31,915] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 17:29:31,935] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 17:29:32,109] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.334 seconds
[2022-05-04 17:30:02,195] {processor.py:163} INFO - Started process (PID=21949) to work on /opt/airflow/dags/ej4.py
[2022-05-04 17:30:02,197] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 17:30:02,199] {logging_mixin.py:109} INFO - [2022-05-04 17:30:02,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 17:30:02,247] {logging_mixin.py:109} INFO - [2022-05-04 17:30:02,239] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 17:30:02,250] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 17:30:02,348] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.159 seconds
[2022-05-04 17:30:32,660] {processor.py:163} INFO - Started process (PID=22009) to work on /opt/airflow/dags/ej4.py
[2022-05-04 17:30:32,664] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 17:30:32,666] {logging_mixin.py:109} INFO - [2022-05-04 17:30:32,666] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 17:30:32,729] {logging_mixin.py:109} INFO - [2022-05-04 17:30:32,721] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 17:30:32,731] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 17:30:32,768] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.116 seconds
[2022-05-04 17:31:03,396] {processor.py:163} INFO - Started process (PID=22069) to work on /opt/airflow/dags/ej4.py
[2022-05-04 17:31:03,398] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej4.py for tasks to queue
[2022-05-04 17:31:03,400] {logging_mixin.py:109} INFO - [2022-05-04 17:31:03,399] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej4.py
[2022-05-04 17:31:03,440] {logging_mixin.py:109} INFO - [2022-05-04 17:31:03,433] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej4.py", line 36, in <module>
    t2 = BashOperator(task_id='bash_task-commands', bash_command=commands)
NameError: name 'commands' is not defined
[2022-05-04 17:31:03,442] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej4.py
[2022-05-04 17:31:03,473] {processor.py:171} INFO - Processing /opt/airflow/dags/ej4.py took 0.082 seconds
