[2022-05-04 15:26:57,234] {processor.py:163} INFO - Started process (PID=15161) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:26:57,243] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:26:57,248] {logging_mixin.py:109} INFO - [2022-05-04 15:26:57,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:26:57,708] {logging_mixin.py:109} INFO - [2022-05-04 15:26:57,378] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:26:57,781] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:26:57,931] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.703 seconds
[2022-05-04 15:27:32,419] {processor.py:163} INFO - Started process (PID=15222) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:27:32,444] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:27:32,485] {logging_mixin.py:109} INFO - [2022-05-04 15:27:32,484] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:27:32,739] {logging_mixin.py:109} INFO - [2022-05-04 15:27:32,709] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:27:32,765] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:27:32,855] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.442 seconds
[2022-05-04 15:28:03,297] {processor.py:163} INFO - Started process (PID=15280) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:28:03,300] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:28:03,305] {logging_mixin.py:109} INFO - [2022-05-04 15:28:03,304] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:28:03,383] {logging_mixin.py:109} INFO - [2022-05-04 15:28:03,376] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:28:03,385] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:28:03,432] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.147 seconds
[2022-05-04 15:28:33,920] {processor.py:163} INFO - Started process (PID=15333) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:28:33,931] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:28:33,934] {logging_mixin.py:109} INFO - [2022-05-04 15:28:33,934] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:28:33,982] {logging_mixin.py:109} INFO - [2022-05-04 15:28:33,969] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:28:33,985] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:28:34,050] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.136 seconds
[2022-05-04 15:29:04,419] {processor.py:163} INFO - Started process (PID=15389) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:29:04,422] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:29:04,423] {logging_mixin.py:109} INFO - [2022-05-04 15:29:04,423] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:29:04,462] {logging_mixin.py:109} INFO - [2022-05-04 15:29:04,457] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:29:04,464] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:29:04,496] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.081 seconds
[2022-05-04 15:29:34,790] {processor.py:163} INFO - Started process (PID=15457) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:29:34,793] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:29:34,794] {logging_mixin.py:109} INFO - [2022-05-04 15:29:34,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:29:34,845] {logging_mixin.py:109} INFO - [2022-05-04 15:29:34,837] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:29:34,847] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:29:34,908] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.123 seconds
[2022-05-04 15:30:05,371] {processor.py:163} INFO - Started process (PID=15517) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:30:05,374] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:30:05,376] {logging_mixin.py:109} INFO - [2022-05-04 15:30:05,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:30:05,406] {logging_mixin.py:109} INFO - [2022-05-04 15:30:05,401] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:30:05,408] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:30:05,442] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.076 seconds
[2022-05-04 15:30:35,806] {processor.py:163} INFO - Started process (PID=15577) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:30:35,810] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:30:35,812] {logging_mixin.py:109} INFO - [2022-05-04 15:30:35,811] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:30:35,881] {logging_mixin.py:109} INFO - [2022-05-04 15:30:35,876] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:30:35,883] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:30:35,919] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.120 seconds
[2022-05-04 15:31:06,442] {processor.py:163} INFO - Started process (PID=15637) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:31:06,444] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:31:06,445] {logging_mixin.py:109} INFO - [2022-05-04 15:31:06,445] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:31:06,485] {logging_mixin.py:109} INFO - [2022-05-04 15:31:06,476] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:31:06,487] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:31:06,531] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.094 seconds
[2022-05-04 15:31:37,101] {processor.py:163} INFO - Started process (PID=15707) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:31:37,105] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:31:37,107] {logging_mixin.py:109} INFO - [2022-05-04 15:31:37,107] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:31:37,173] {logging_mixin.py:109} INFO - [2022-05-04 15:31:37,165] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:31:37,176] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:31:37,215] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.119 seconds
[2022-05-04 15:32:07,803] {processor.py:163} INFO - Started process (PID=15768) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:32:07,805] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:32:07,807] {logging_mixin.py:109} INFO - [2022-05-04 15:32:07,806] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:32:07,869] {logging_mixin.py:109} INFO - [2022-05-04 15:32:07,858] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:32:07,871] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:32:07,915] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.121 seconds
[2022-05-04 15:32:38,758] {processor.py:163} INFO - Started process (PID=15828) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:32:38,760] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:32:38,761] {logging_mixin.py:109} INFO - [2022-05-04 15:32:38,761] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:32:38,794] {logging_mixin.py:109} INFO - [2022-05-04 15:32:38,790] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:32:38,795] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:32:38,826] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.072 seconds
[2022-05-04 15:33:09,193] {processor.py:163} INFO - Started process (PID=15899) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:33:09,200] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:33:09,203] {logging_mixin.py:109} INFO - [2022-05-04 15:33:09,203] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:33:09,252] {logging_mixin.py:109} INFO - [2022-05-04 15:33:09,243] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:33:09,254] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:33:09,308] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.121 seconds
[2022-05-04 15:33:40,072] {processor.py:163} INFO - Started process (PID=15960) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:33:40,074] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:33:40,074] {logging_mixin.py:109} INFO - [2022-05-04 15:33:40,074] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:33:40,109] {logging_mixin.py:109} INFO - [2022-05-04 15:33:40,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:33:40,111] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:33:40,145] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 15:34:10,586] {processor.py:163} INFO - Started process (PID=16020) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:34:10,588] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:34:10,589] {logging_mixin.py:109} INFO - [2022-05-04 15:34:10,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:34:10,622] {logging_mixin.py:109} INFO - [2022-05-04 15:34:10,616] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:34:10,623] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:34:10,653] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.071 seconds
[2022-05-04 15:34:40,989] {processor.py:163} INFO - Started process (PID=16090) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:34:40,991] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:34:40,992] {logging_mixin.py:109} INFO - [2022-05-04 15:34:40,992] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:34:41,028] {logging_mixin.py:109} INFO - [2022-05-04 15:34:41,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:34:41,030] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:34:41,061] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.075 seconds
[2022-05-04 15:35:11,825] {processor.py:163} INFO - Started process (PID=16150) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:35:11,827] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:35:11,828] {logging_mixin.py:109} INFO - [2022-05-04 15:35:11,828] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:35:11,848] {logging_mixin.py:109} INFO - [2022-05-04 15:35:11,845] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:35:11,849] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:35:11,872] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.052 seconds
[2022-05-04 15:35:42,426] {processor.py:163} INFO - Started process (PID=16220) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:35:42,428] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:35:42,429] {logging_mixin.py:109} INFO - [2022-05-04 15:35:42,429] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:35:42,452] {logging_mixin.py:109} INFO - [2022-05-04 15:35:42,448] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:35:42,454] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:35:42,481] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.057 seconds
[2022-05-04 15:36:12,590] {processor.py:163} INFO - Started process (PID=16279) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:36:12,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:36:12,592] {logging_mixin.py:109} INFO - [2022-05-04 15:36:12,592] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:36:12,620] {logging_mixin.py:109} INFO - [2022-05-04 15:36:12,614] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:36:12,622] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:36:12,649] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.062 seconds
[2022-05-04 15:36:43,204] {processor.py:163} INFO - Started process (PID=16350) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:36:43,207] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:36:43,208] {logging_mixin.py:109} INFO - [2022-05-04 15:36:43,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:36:43,237] {logging_mixin.py:109} INFO - [2022-05-04 15:36:43,232] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:36:43,239] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:36:43,276] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 15:37:13,463] {processor.py:163} INFO - Started process (PID=16410) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:37:13,465] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:37:13,466] {logging_mixin.py:109} INFO - [2022-05-04 15:37:13,466] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:37:13,489] {logging_mixin.py:109} INFO - [2022-05-04 15:37:13,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:37:13,490] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:37:13,519] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.059 seconds
[2022-05-04 15:37:43,685] {processor.py:163} INFO - Started process (PID=16483) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:37:43,686] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:37:43,687] {logging_mixin.py:109} INFO - [2022-05-04 15:37:43,687] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:37:43,717] {logging_mixin.py:109} INFO - [2022-05-04 15:37:43,712] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:37:43,718] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:37:43,748] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.068 seconds
[2022-05-04 15:38:13,962] {processor.py:163} INFO - Started process (PID=16533) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:38:13,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:38:13,965] {logging_mixin.py:109} INFO - [2022-05-04 15:38:13,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:38:13,984] {logging_mixin.py:109} INFO - [2022-05-04 15:38:13,979] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:38:13,987] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:38:14,014] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.054 seconds
[2022-05-04 15:38:44,209] {processor.py:163} INFO - Started process (PID=16599) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:38:44,210] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:38:44,211] {logging_mixin.py:109} INFO - [2022-05-04 15:38:44,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:38:44,236] {logging_mixin.py:109} INFO - [2022-05-04 15:38:44,232] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:38:44,237] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:38:44,261] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.055 seconds
[2022-05-04 15:39:14,617] {processor.py:163} INFO - Started process (PID=16660) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:39:14,618] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:39:14,619] {logging_mixin.py:109} INFO - [2022-05-04 15:39:14,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:39:14,641] {logging_mixin.py:109} INFO - [2022-05-04 15:39:14,636] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:39:14,642] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:39:14,667] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.054 seconds
[2022-05-04 15:39:45,446] {processor.py:163} INFO - Started process (PID=16728) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:39:45,447] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:39:45,448] {logging_mixin.py:109} INFO - [2022-05-04 15:39:45,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:39:45,470] {logging_mixin.py:109} INFO - [2022-05-04 15:39:45,465] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:39:45,471] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:39:45,498] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.055 seconds
[2022-05-04 15:40:15,707] {processor.py:163} INFO - Started process (PID=16788) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:40:15,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:40:15,710] {logging_mixin.py:109} INFO - [2022-05-04 15:40:15,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:40:15,735] {logging_mixin.py:109} INFO - [2022-05-04 15:40:15,731] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:40:15,736] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:40:15,764] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.060 seconds
[2022-05-04 15:40:46,071] {processor.py:163} INFO - Started process (PID=16858) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:40:46,073] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:40:46,075] {logging_mixin.py:109} INFO - [2022-05-04 15:40:46,074] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:40:46,104] {logging_mixin.py:109} INFO - [2022-05-04 15:40:46,099] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:40:46,105] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:40:46,135] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.068 seconds
[2022-05-04 15:41:16,372] {processor.py:163} INFO - Started process (PID=16917) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:41:16,374] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:41:16,375] {logging_mixin.py:109} INFO - [2022-05-04 15:41:16,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:41:16,405] {logging_mixin.py:109} INFO - [2022-05-04 15:41:16,398] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:41:16,407] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:41:16,435] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.066 seconds
[2022-05-04 15:41:46,479] {processor.py:163} INFO - Started process (PID=16985) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:41:46,480] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:41:46,480] {logging_mixin.py:109} INFO - [2022-05-04 15:41:46,480] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:41:46,496] {logging_mixin.py:109} INFO - [2022-05-04 15:41:46,494] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:41:46,497] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:41:46,520] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.045 seconds
[2022-05-04 15:42:17,124] {processor.py:163} INFO - Started process (PID=17044) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:42:17,126] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:42:17,126] {logging_mixin.py:109} INFO - [2022-05-04 15:42:17,126] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:42:17,148] {logging_mixin.py:109} INFO - [2022-05-04 15:42:17,144] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:42:17,150] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:42:17,179] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.058 seconds
[2022-05-04 15:43:03,452] {processor.py:163} INFO - Started process (PID=17091) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:43:03,454] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:43:03,457] {logging_mixin.py:109} INFO - [2022-05-04 15:43:03,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:43:03,559] {logging_mixin.py:109} INFO - [2022-05-04 15:43:03,555] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:43:03,561] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:43:03,661] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.227 seconds
[2022-05-04 15:48:01,157] {processor.py:163} INFO - Started process (PID=17142) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:48:01,159] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:48:01,160] {logging_mixin.py:109} INFO - [2022-05-04 15:48:01,160] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:48:01,187] {logging_mixin.py:109} INFO - [2022-05-04 15:48:01,182] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:48:01,189] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:48:01,218] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.066 seconds
[2022-05-04 15:48:31,515] {processor.py:163} INFO - Started process (PID=17201) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:48:31,517] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:48:31,518] {logging_mixin.py:109} INFO - [2022-05-04 15:48:31,518] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:48:31,558] {logging_mixin.py:109} INFO - [2022-05-04 15:48:31,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:48:31,560] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:48:31,588] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.076 seconds
[2022-05-04 15:49:01,666] {processor.py:163} INFO - Started process (PID=17270) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:49:01,668] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:49:01,670] {logging_mixin.py:109} INFO - [2022-05-04 15:49:01,669] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:49:01,714] {logging_mixin.py:109} INFO - [2022-05-04 15:49:01,710] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:49:01,716] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:49:01,744] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.080 seconds
[2022-05-04 15:49:32,430] {processor.py:163} INFO - Started process (PID=17331) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:49:32,431] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:49:32,432] {logging_mixin.py:109} INFO - [2022-05-04 15:49:32,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:49:32,476] {logging_mixin.py:109} INFO - [2022-05-04 15:49:32,468] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:49:32,478] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:49:32,504] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 15:50:03,177] {processor.py:163} INFO - Started process (PID=17399) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:50:03,180] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:50:03,181] {logging_mixin.py:109} INFO - [2022-05-04 15:50:03,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:50:03,225] {logging_mixin.py:109} INFO - [2022-05-04 15:50:03,217] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:50:03,227] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:50:03,260] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.086 seconds
[2022-05-04 15:50:33,907] {processor.py:163} INFO - Started process (PID=17460) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:50:33,908] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:50:33,909] {logging_mixin.py:109} INFO - [2022-05-04 15:50:33,909] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:50:33,940] {logging_mixin.py:109} INFO - [2022-05-04 15:50:33,936] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:50:33,942] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:50:33,964] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.061 seconds
[2022-05-04 15:51:04,613] {processor.py:163} INFO - Started process (PID=17530) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:51:04,614] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:51:04,616] {logging_mixin.py:109} INFO - [2022-05-04 15:51:04,616] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:51:04,657] {logging_mixin.py:109} INFO - [2022-05-04 15:51:04,648] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:51:04,660] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:51:04,685] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.077 seconds
[2022-05-04 15:51:34,976] {processor.py:163} INFO - Started process (PID=17590) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:51:34,978] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:51:34,978] {logging_mixin.py:109} INFO - [2022-05-04 15:51:34,978] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:51:35,020] {logging_mixin.py:109} INFO - [2022-05-04 15:51:35,012] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:51:35,023] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:51:35,049] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.076 seconds
[2022-05-04 15:52:05,553] {processor.py:163} INFO - Started process (PID=17660) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:52:05,555] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:52:05,556] {logging_mixin.py:109} INFO - [2022-05-04 15:52:05,556] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:52:05,598] {logging_mixin.py:109} INFO - [2022-05-04 15:52:05,589] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:52:05,600] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:52:05,629] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.079 seconds
[2022-05-04 15:52:36,532] {processor.py:163} INFO - Started process (PID=17730) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:52:36,534] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:52:36,535] {logging_mixin.py:109} INFO - [2022-05-04 15:52:36,535] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:52:36,565] {logging_mixin.py:109} INFO - [2022-05-04 15:52:36,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:52:36,567] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:52:36,601] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.075 seconds
[2022-05-04 15:53:07,005] {processor.py:163} INFO - Started process (PID=17790) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:53:07,007] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:53:07,008] {logging_mixin.py:109} INFO - [2022-05-04 15:53:07,008] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:53:07,049] {logging_mixin.py:109} INFO - [2022-05-04 15:53:07,042] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:53:07,052] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:53:07,077] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.076 seconds
[2022-05-04 15:53:37,745] {processor.py:163} INFO - Started process (PID=17859) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:53:37,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:53:37,748] {logging_mixin.py:109} INFO - [2022-05-04 15:53:37,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:53:37,790] {logging_mixin.py:109} INFO - [2022-05-04 15:53:37,782] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:53:37,792] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:53:37,820] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 15:54:08,214] {processor.py:163} INFO - Started process (PID=17919) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:54:08,216] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:54:08,217] {logging_mixin.py:109} INFO - [2022-05-04 15:54:08,216] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:54:08,258] {logging_mixin.py:109} INFO - [2022-05-04 15:54:08,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:54:08,260] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:54:08,288] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.077 seconds
[2022-05-04 15:54:38,532] {processor.py:163} INFO - Started process (PID=17988) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:54:38,533] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:54:38,534] {logging_mixin.py:109} INFO - [2022-05-04 15:54:38,534] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:54:38,583] {logging_mixin.py:109} INFO - [2022-05-04 15:54:38,573] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:54:38,585] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:54:38,613] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 15:55:09,129] {processor.py:163} INFO - Started process (PID=18055) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:55:09,131] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:55:09,132] {logging_mixin.py:109} INFO - [2022-05-04 15:55:09,132] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:55:09,166] {logging_mixin.py:109} INFO - [2022-05-04 15:55:09,162] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:55:09,167] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:55:09,197] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.072 seconds
[2022-05-04 15:55:39,823] {processor.py:163} INFO - Started process (PID=18119) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:55:39,826] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:55:39,827] {logging_mixin.py:109} INFO - [2022-05-04 15:55:39,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:55:39,858] {logging_mixin.py:109} INFO - [2022-05-04 15:55:39,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:55:39,861] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:55:39,887] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.067 seconds
[2022-05-04 15:56:10,597] {processor.py:163} INFO - Started process (PID=18188) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:56:10,599] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:56:10,600] {logging_mixin.py:109} INFO - [2022-05-04 15:56:10,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:56:10,641] {logging_mixin.py:109} INFO - [2022-05-04 15:56:10,635] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:56:10,642] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:56:10,667] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.074 seconds
[2022-05-04 15:56:41,187] {processor.py:163} INFO - Started process (PID=18248) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:56:41,189] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:56:41,191] {logging_mixin.py:109} INFO - [2022-05-04 15:56:41,191] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:56:41,231] {logging_mixin.py:109} INFO - [2022-05-04 15:56:41,224] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:56:41,233] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:56:41,261] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.077 seconds
[2022-05-04 15:57:11,384] {processor.py:163} INFO - Started process (PID=18317) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:57:11,387] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:57:11,388] {logging_mixin.py:109} INFO - [2022-05-04 15:57:11,388] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:57:11,427] {logging_mixin.py:109} INFO - [2022-05-04 15:57:11,422] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:57:11,430] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:57:11,454] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.073 seconds
[2022-05-04 15:57:41,586] {processor.py:163} INFO - Started process (PID=18378) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:57:41,588] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:57:41,589] {logging_mixin.py:109} INFO - [2022-05-04 15:57:41,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:57:41,629] {logging_mixin.py:109} INFO - [2022-05-04 15:57:41,623] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:57:41,631] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:57:41,656] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.073 seconds
[2022-05-04 15:58:12,586] {processor.py:163} INFO - Started process (PID=18447) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:58:12,587] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:58:12,588] {logging_mixin.py:109} INFO - [2022-05-04 15:58:12,588] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:58:12,623] {logging_mixin.py:109} INFO - [2022-05-04 15:58:12,618] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:58:12,626] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:58:12,649] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.066 seconds
[2022-05-04 15:58:42,995] {processor.py:163} INFO - Started process (PID=18516) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:58:42,998] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:58:42,999] {logging_mixin.py:109} INFO - [2022-05-04 15:58:42,999] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:58:43,038] {logging_mixin.py:109} INFO - [2022-05-04 15:58:43,032] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:58:43,039] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:58:43,063] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.072 seconds
[2022-05-04 15:59:13,805] {processor.py:163} INFO - Started process (PID=18575) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:59:13,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:59:13,807] {logging_mixin.py:109} INFO - [2022-05-04 15:59:13,807] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:59:13,851] {logging_mixin.py:109} INFO - [2022-05-04 15:59:13,845] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:59:13,854] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:59:13,884] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.082 seconds
[2022-05-04 15:59:44,475] {processor.py:163} INFO - Started process (PID=18644) to work on /opt/airflow/dags/ej8.py
[2022-05-04 15:59:44,477] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 15:59:44,478] {logging_mixin.py:109} INFO - [2022-05-04 15:59:44,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 15:59:44,520] {logging_mixin.py:109} INFO - [2022-05-04 15:59:44,512] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 15:59:44,522] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 15:59:44,545] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.074 seconds
[2022-05-04 16:00:14,987] {processor.py:163} INFO - Started process (PID=18703) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:00:14,989] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:00:14,991] {logging_mixin.py:109} INFO - [2022-05-04 16:00:14,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:00:15,029] {logging_mixin.py:109} INFO - [2022-05-04 16:00:15,023] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:00:15,031] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:00:15,067] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:00:45,696] {processor.py:163} INFO - Started process (PID=18774) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:00:45,699] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:00:45,700] {logging_mixin.py:109} INFO - [2022-05-04 16:00:45,700] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:00:45,741] {logging_mixin.py:109} INFO - [2022-05-04 16:00:45,735] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:00:45,743] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:00:45,771] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.080 seconds
[2022-05-04 16:01:16,252] {processor.py:163} INFO - Started process (PID=18834) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:01:16,254] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:01:16,255] {logging_mixin.py:109} INFO - [2022-05-04 16:01:16,255] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:01:16,293] {logging_mixin.py:109} INFO - [2022-05-04 16:01:16,283] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:01:16,294] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:01:16,325] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 16:01:46,822] {processor.py:163} INFO - Started process (PID=18903) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:01:46,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:01:46,826] {logging_mixin.py:109} INFO - [2022-05-04 16:01:46,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:01:46,869] {logging_mixin.py:109} INFO - [2022-05-04 16:01:46,862] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:01:46,871] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:01:46,905] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.089 seconds
[2022-05-04 16:02:17,671] {processor.py:163} INFO - Started process (PID=18962) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:02:17,673] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:02:17,675] {logging_mixin.py:109} INFO - [2022-05-04 16:02:17,675] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:02:17,724] {logging_mixin.py:109} INFO - [2022-05-04 16:02:17,716] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:02:17,726] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:02:17,767] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.102 seconds
[2022-05-04 16:02:48,062] {processor.py:163} INFO - Started process (PID=19032) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:02:48,063] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:02:48,064] {logging_mixin.py:109} INFO - [2022-05-04 16:02:48,064] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:02:48,103] {logging_mixin.py:109} INFO - [2022-05-04 16:02:48,098] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:02:48,105] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:02:48,136] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 16:03:18,250] {processor.py:163} INFO - Started process (PID=19093) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:03:18,252] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:03:18,254] {logging_mixin.py:109} INFO - [2022-05-04 16:03:18,253] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:03:18,293] {logging_mixin.py:109} INFO - [2022-05-04 16:03:18,286] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:03:18,296] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:03:18,328] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:03:48,737] {processor.py:163} INFO - Started process (PID=19162) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:03:48,739] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:03:48,740] {logging_mixin.py:109} INFO - [2022-05-04 16:03:48,740] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:03:48,772] {logging_mixin.py:109} INFO - [2022-05-04 16:03:48,767] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:03:48,774] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:03:48,804] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.070 seconds
[2022-05-04 16:04:19,119] {processor.py:163} INFO - Started process (PID=19222) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:04:19,122] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:04:19,123] {logging_mixin.py:109} INFO - [2022-05-04 16:04:19,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:04:19,162] {logging_mixin.py:109} INFO - [2022-05-04 16:04:19,156] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:04:19,165] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:04:19,196] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.083 seconds
[2022-05-04 16:04:49,789] {processor.py:163} INFO - Started process (PID=19290) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:04:49,791] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:04:49,793] {logging_mixin.py:109} INFO - [2022-05-04 16:04:49,793] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:04:49,827] {logging_mixin.py:109} INFO - [2022-05-04 16:04:49,821] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:04:49,829] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:04:49,858] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.074 seconds
[2022-05-04 16:05:20,042] {processor.py:163} INFO - Started process (PID=19353) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:05:20,044] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:05:20,046] {logging_mixin.py:109} INFO - [2022-05-04 16:05:20,045] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:05:20,076] {logging_mixin.py:109} INFO - [2022-05-04 16:05:20,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:05:20,078] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:05:20,105] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.067 seconds
[2022-05-04 16:05:50,596] {processor.py:163} INFO - Started process (PID=19414) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:05:50,598] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:05:50,600] {logging_mixin.py:109} INFO - [2022-05-04 16:05:50,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:05:50,647] {logging_mixin.py:109} INFO - [2022-05-04 16:05:50,640] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:05:50,648] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:05:50,675] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.088 seconds
[2022-05-04 16:06:21,132] {processor.py:163} INFO - Started process (PID=19485) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:06:21,134] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:06:21,135] {logging_mixin.py:109} INFO - [2022-05-04 16:06:21,135] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:06:21,168] {logging_mixin.py:109} INFO - [2022-05-04 16:06:21,162] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:06:21,170] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:06:21,202] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.075 seconds
[2022-05-04 16:06:52,056] {processor.py:163} INFO - Started process (PID=19544) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:06:52,058] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:06:52,059] {logging_mixin.py:109} INFO - [2022-05-04 16:06:52,059] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:06:52,090] {logging_mixin.py:109} INFO - [2022-05-04 16:06:52,085] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:06:52,093] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:06:52,124] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.071 seconds
[2022-05-04 16:07:22,732] {processor.py:163} INFO - Started process (PID=19612) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:07:22,734] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:07:22,736] {logging_mixin.py:109} INFO - [2022-05-04 16:07:22,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:07:22,781] {logging_mixin.py:109} INFO - [2022-05-04 16:07:22,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:07:22,784] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:07:22,813] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.089 seconds
[2022-05-04 16:07:53,429] {processor.py:163} INFO - Started process (PID=19672) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:07:53,431] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:07:53,432] {logging_mixin.py:109} INFO - [2022-05-04 16:07:53,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:07:53,476] {logging_mixin.py:109} INFO - [2022-05-04 16:07:53,469] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:07:53,478] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:07:53,509] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.085 seconds
[2022-05-04 16:08:23,640] {processor.py:163} INFO - Started process (PID=19742) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:08:23,643] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:08:23,644] {logging_mixin.py:109} INFO - [2022-05-04 16:08:23,644] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:08:23,681] {logging_mixin.py:109} INFO - [2022-05-04 16:08:23,674] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:08:23,683] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:08:23,712] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.077 seconds
[2022-05-04 16:08:53,861] {processor.py:163} INFO - Started process (PID=19802) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:08:53,863] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:08:53,865] {logging_mixin.py:109} INFO - [2022-05-04 16:08:53,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:08:53,909] {logging_mixin.py:109} INFO - [2022-05-04 16:08:53,901] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:08:53,912] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:08:53,947] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.090 seconds
[2022-05-04 16:09:24,526] {processor.py:163} INFO - Started process (PID=19873) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:09:24,529] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:09:24,530] {logging_mixin.py:109} INFO - [2022-05-04 16:09:24,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:09:24,564] {logging_mixin.py:109} INFO - [2022-05-04 16:09:24,558] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:09:24,566] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:09:24,604] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.082 seconds
[2022-05-04 16:09:55,144] {processor.py:163} INFO - Started process (PID=19934) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:09:55,146] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:09:55,147] {logging_mixin.py:109} INFO - [2022-05-04 16:09:55,147] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:09:55,189] {logging_mixin.py:109} INFO - [2022-05-04 16:09:55,182] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:09:55,191] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:09:55,217] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 16:10:25,491] {processor.py:163} INFO - Started process (PID=20003) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:10:25,494] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:10:25,495] {logging_mixin.py:109} INFO - [2022-05-04 16:10:25,495] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:10:25,530] {logging_mixin.py:109} INFO - [2022-05-04 16:10:25,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:10:25,532] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:10:25,565] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.079 seconds
[2022-05-04 16:10:55,712] {processor.py:163} INFO - Started process (PID=20063) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:10:55,714] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:10:55,716] {logging_mixin.py:109} INFO - [2022-05-04 16:10:55,716] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:10:55,764] {logging_mixin.py:109} INFO - [2022-05-04 16:10:55,757] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:10:55,767] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:10:55,796] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.092 seconds
[2022-05-04 16:11:26,369] {processor.py:163} INFO - Started process (PID=20133) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:11:26,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:11:26,373] {logging_mixin.py:109} INFO - [2022-05-04 16:11:26,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:11:26,410] {logging_mixin.py:109} INFO - [2022-05-04 16:11:26,404] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:11:26,412] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:11:26,441] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 16:11:56,872] {processor.py:163} INFO - Started process (PID=20192) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:11:56,875] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:11:56,876] {logging_mixin.py:109} INFO - [2022-05-04 16:11:56,876] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:11:56,922] {logging_mixin.py:109} INFO - [2022-05-04 16:11:56,915] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:11:56,925] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:11:56,953] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.085 seconds
[2022-05-04 16:12:27,057] {processor.py:163} INFO - Started process (PID=20258) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:12:27,059] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:12:27,061] {logging_mixin.py:109} INFO - [2022-05-04 16:12:27,061] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:12:27,102] {logging_mixin.py:109} INFO - [2022-05-04 16:12:27,096] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:12:27,104] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:12:27,132] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.082 seconds
[2022-05-04 16:12:57,289] {processor.py:163} INFO - Started process (PID=20321) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:12:57,291] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:12:57,293] {logging_mixin.py:109} INFO - [2022-05-04 16:12:57,293] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:12:57,333] {logging_mixin.py:109} INFO - [2022-05-04 16:12:57,326] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:12:57,335] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:12:57,365] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:13:27,756] {processor.py:163} INFO - Started process (PID=20382) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:13:27,758] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:13:27,759] {logging_mixin.py:109} INFO - [2022-05-04 16:13:27,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:13:27,802] {logging_mixin.py:109} INFO - [2022-05-04 16:13:27,794] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:13:27,805] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:13:27,840] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.088 seconds
[2022-05-04 16:13:58,079] {processor.py:163} INFO - Started process (PID=20454) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:13:58,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:13:58,083] {logging_mixin.py:109} INFO - [2022-05-04 16:13:58,082] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:13:58,120] {logging_mixin.py:109} INFO - [2022-05-04 16:13:58,112] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:13:58,122] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:13:58,151] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.078 seconds
[2022-05-04 16:14:28,233] {processor.py:163} INFO - Started process (PID=20514) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:14:28,234] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:14:28,235] {logging_mixin.py:109} INFO - [2022-05-04 16:14:28,235] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:14:28,273] {logging_mixin.py:109} INFO - [2022-05-04 16:14:28,267] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:14:28,275] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:14:28,307] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.079 seconds
[2022-05-04 16:14:59,048] {processor.py:163} INFO - Started process (PID=20584) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:14:59,051] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:14:59,052] {logging_mixin.py:109} INFO - [2022-05-04 16:14:59,052] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:14:59,094] {logging_mixin.py:109} INFO - [2022-05-04 16:14:59,086] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:14:59,096] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:14:59,129] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.085 seconds
[2022-05-04 16:15:29,352] {processor.py:163} INFO - Started process (PID=20644) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:15:29,354] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:15:29,355] {logging_mixin.py:109} INFO - [2022-05-04 16:15:29,355] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:15:29,398] {logging_mixin.py:109} INFO - [2022-05-04 16:15:29,390] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:15:29,401] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:15:29,431] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:15:59,829] {processor.py:163} INFO - Started process (PID=20714) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:15:59,832] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:15:59,833] {logging_mixin.py:109} INFO - [2022-05-04 16:15:59,833] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:15:59,879] {logging_mixin.py:109} INFO - [2022-05-04 16:15:59,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:15:59,881] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:15:59,908] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:16:30,325] {processor.py:163} INFO - Started process (PID=20775) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:16:30,326] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:16:30,328] {logging_mixin.py:109} INFO - [2022-05-04 16:16:30,327] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:16:30,373] {logging_mixin.py:109} INFO - [2022-05-04 16:16:30,365] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:16:30,375] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:16:30,409] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.088 seconds
[2022-05-04 16:17:00,626] {processor.py:163} INFO - Started process (PID=20845) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:17:00,628] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:17:00,630] {logging_mixin.py:109} INFO - [2022-05-04 16:17:00,629] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:17:00,672] {logging_mixin.py:109} INFO - [2022-05-04 16:17:00,664] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:17:00,674] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:17:00,706] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.084 seconds
[2022-05-04 16:17:30,903] {processor.py:163} INFO - Started process (PID=20905) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:17:30,906] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:17:30,907] {logging_mixin.py:109} INFO - [2022-05-04 16:17:30,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:17:30,949] {logging_mixin.py:109} INFO - [2022-05-04 16:17:30,942] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:17:30,952] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:17:30,981] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.083 seconds
[2022-05-04 16:18:01,488] {processor.py:163} INFO - Started process (PID=20975) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:18:01,490] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:18:01,491] {logging_mixin.py:109} INFO - [2022-05-04 16:18:01,491] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:18:01,532] {logging_mixin.py:109} INFO - [2022-05-04 16:18:01,526] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:18:01,534] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:18:01,566] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.082 seconds
[2022-05-04 16:18:31,837] {processor.py:163} INFO - Started process (PID=21035) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:18:31,839] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:18:31,840] {logging_mixin.py:109} INFO - [2022-05-04 16:18:31,840] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:18:31,883] {logging_mixin.py:109} INFO - [2022-05-04 16:18:31,875] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:18:31,886] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:18:31,913] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.080 seconds
[2022-05-04 16:19:02,650] {processor.py:163} INFO - Started process (PID=21105) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:19:02,652] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:19:02,654] {logging_mixin.py:109} INFO - [2022-05-04 16:19:02,653] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:19:02,700] {logging_mixin.py:109} INFO - [2022-05-04 16:19:02,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:19:02,702] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:19:02,736] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.090 seconds
[2022-05-04 16:19:33,141] {processor.py:163} INFO - Started process (PID=21165) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:19:33,143] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:19:33,145] {logging_mixin.py:109} INFO - [2022-05-04 16:19:33,145] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:19:33,179] {logging_mixin.py:109} INFO - [2022-05-04 16:19:33,174] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:19:33,181] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:19:33,210] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.074 seconds
[2022-05-04 16:20:03,852] {processor.py:163} INFO - Started process (PID=21225) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:20:03,853] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:20:03,854] {logging_mixin.py:109} INFO - [2022-05-04 16:20:03,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:20:03,884] {logging_mixin.py:109} INFO - [2022-05-04 16:20:03,879] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:20:03,886] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:20:03,915] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.068 seconds
[2022-05-04 16:20:34,427] {processor.py:163} INFO - Started process (PID=21296) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:20:34,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:20:34,432] {logging_mixin.py:109} INFO - [2022-05-04 16:20:34,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:20:34,475] {logging_mixin.py:109} INFO - [2022-05-04 16:20:34,468] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:20:34,477] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:20:34,508] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.088 seconds
[2022-05-04 16:21:05,026] {processor.py:163} INFO - Started process (PID=21356) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:21:05,030] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:21:05,033] {logging_mixin.py:109} INFO - [2022-05-04 16:21:05,032] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:21:05,095] {logging_mixin.py:109} INFO - [2022-05-04 16:21:05,084] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:21:05,098] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:21:05,133] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.113 seconds
[2022-05-04 16:21:35,754] {processor.py:163} INFO - Started process (PID=21426) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:21:35,757] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:21:35,759] {logging_mixin.py:109} INFO - [2022-05-04 16:21:35,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:21:35,806] {logging_mixin.py:109} INFO - [2022-05-04 16:21:35,799] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:21:35,808] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:21:35,840] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.094 seconds
[2022-05-04 16:22:06,562] {processor.py:163} INFO - Started process (PID=21485) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:22:06,564] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:22:06,566] {logging_mixin.py:109} INFO - [2022-05-04 16:22:06,566] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:22:06,606] {logging_mixin.py:109} INFO - [2022-05-04 16:22:06,599] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:22:06,608] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:22:06,635] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.079 seconds
[2022-05-04 16:22:37,242] {processor.py:163} INFO - Started process (PID=21555) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:22:37,245] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:22:37,247] {logging_mixin.py:109} INFO - [2022-05-04 16:22:37,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:22:37,292] {logging_mixin.py:109} INFO - [2022-05-04 16:22:37,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:22:37,295] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:22:37,333] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.097 seconds
[2022-05-04 16:23:07,770] {processor.py:163} INFO - Started process (PID=21615) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:23:07,773] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:23:07,774] {logging_mixin.py:109} INFO - [2022-05-04 16:23:07,773] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:23:07,811] {logging_mixin.py:109} INFO - [2022-05-04 16:23:07,805] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:23:07,812] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:23:07,840] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.075 seconds
[2022-05-04 16:23:38,576] {processor.py:163} INFO - Started process (PID=21686) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:23:38,579] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:23:38,581] {logging_mixin.py:109} INFO - [2022-05-04 16:23:38,580] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:23:38,625] {logging_mixin.py:109} INFO - [2022-05-04 16:23:38,618] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:23:38,628] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:23:38,655] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.087 seconds
[2022-05-04 16:24:09,207] {processor.py:163} INFO - Started process (PID=21747) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:24:09,210] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:24:09,212] {logging_mixin.py:109} INFO - [2022-05-04 16:24:09,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:24:09,256] {logging_mixin.py:109} INFO - [2022-05-04 16:24:09,248] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:24:09,258] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:24:09,292] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.092 seconds
[2022-05-04 16:24:39,885] {processor.py:163} INFO - Started process (PID=21816) to work on /opt/airflow/dags/ej8.py
[2022-05-04 16:24:39,887] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 16:24:39,889] {logging_mixin.py:109} INFO - [2022-05-04 16:24:39,888] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 16:24:39,931] {logging_mixin.py:109} INFO - [2022-05-04 16:24:39,923] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 16:24:39,933] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 16:24:39,968] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.090 seconds
[2022-05-04 17:29:31,800] {processor.py:163} INFO - Started process (PID=21887) to work on /opt/airflow/dags/ej8.py
[2022-05-04 17:29:31,805] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 17:29:31,809] {logging_mixin.py:109} INFO - [2022-05-04 17:29:31,809] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 17:29:31,891] {logging_mixin.py:109} INFO - [2022-05-04 17:29:31,876] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 17:29:31,894] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 17:29:32,100] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.309 seconds
[2022-05-04 17:30:02,191] {processor.py:163} INFO - Started process (PID=21948) to work on /opt/airflow/dags/ej8.py
[2022-05-04 17:30:02,194] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 17:30:02,196] {logging_mixin.py:109} INFO - [2022-05-04 17:30:02,196] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 17:30:02,242] {logging_mixin.py:109} INFO - [2022-05-04 17:30:02,234] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 17:30:02,245] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 17:30:02,356] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.170 seconds
[2022-05-04 17:30:32,658] {processor.py:163} INFO - Started process (PID=22008) to work on /opt/airflow/dags/ej8.py
[2022-05-04 17:30:32,662] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 17:30:32,664] {logging_mixin.py:109} INFO - [2022-05-04 17:30:32,664] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 17:30:32,729] {logging_mixin.py:109} INFO - [2022-05-04 17:30:32,721] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 17:30:32,731] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 17:30:32,771] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.122 seconds
[2022-05-04 17:31:03,395] {processor.py:163} INFO - Started process (PID=22068) to work on /opt/airflow/dags/ej8.py
[2022-05-04 17:31:03,397] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej8.py for tasks to queue
[2022-05-04 17:31:03,398] {logging_mixin.py:109} INFO - [2022-05-04 17:31:03,398] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej8.py
[2022-05-04 17:31:03,440] {logging_mixin.py:109} INFO - [2022-05-04 17:31:03,434] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej8.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej8.py", line 4, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-04 17:31:03,442] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej8.py
[2022-05-04 17:31:03,476] {processor.py:171} INFO - Processing /opt/airflow/dags/ej8.py took 0.086 seconds
